console.log("init.js carregado");

initdata();

function initdata() {
  // Utilizador inicial
  if (!localStorage.user) {
    const user = [
      {
        username: "António Amorim",
        avatar: "/img/users/40240119.jpg",
        pontos: "3500",
        email: "40240119@esmad.ipp.pt",
        password: "40240119",
        private: false,
        admin: false,
      },
      {
        username: "Gabriel Paiva",
        avatar: "/img/users/40240137.jpg",
        pontos: "0",
        email: "40240137@esmad.ipp.pt",
        password: "40240137",
        private: false,
        admin: true,
      },
    ];
    localStorage.setItem("user", JSON.stringify(user));
  }
  // Aeroportos
  if (!localStorage.aeroportos) {
    const aeroportos = [
      {
        codigo: "OPO",
        cidade: "Porto",
        pais: "Portugal",
        location: { latitude: 41.2421, longitude: -8.6781 },
      },
      {
        codigo: "LIS",
        cidade: "Lisboa",
        pais: "Portugal",
        location: { latitude: 38.7742, longitude: -9.1342 },
      },
      {
        codigo: "LHR",
        cidade: "Londres",
        pais: "Reino Unido",
        location: { latitude: 51.47, longitude: -0.4543 },
      },
      {
        codigo: "LGW",
        cidade: "Londres",
        pais: "Reino Unido",
        location: { latitude: 51.1537, longitude: -0.1821 },
      },
      {
        codigo: "STN",
        cidade: "Londres",
        pais: "Reino Unido",
        location: { latitude: 51.885, longitude: 0.235 },
      },
      {
        codigo: "LTN",
        cidade: "Londres",
        pais: "Reino Unido",
        location: { latitude: 51.8747, longitude: -0.3683 },
      },
      {
        codigo: "LCY",
        cidade: "Londres",
        pais: "Reino Unido",
        location: { latitude: 51.5053, longitude: 0.0553 },
      },
      {
        codigo: "CDG",
        cidade: "Paris",
        pais: "França",
        location: { latitude: 49.0097, longitude: 2.5479 },
      },
      {
        codigo: "ORY",
        cidade: "Paris",
        pais: "França",
        location: { latitude: 48.7262, longitude: 2.3652 },
      },
      {
        codigo: "BVA",
        cidade: "Paris",
        pais: "França",
        location: { latitude: 49.4544, longitude: 2.1128 },
      },
      {
        codigo: "AMS",
        cidade: "Amesterdão",
        pais: "Países Baixos",
        location: { latitude: 52.3105, longitude: 4.7683 },
      },
      {
        codigo: "MAD",
        cidade: "Madrid",
        pais: "Espanha",
        location: { latitude: 40.4983, longitude: -3.5676 },
      },
      {
        codigo: "FCO",
        cidade: "Roma",
        pais: "Itália",
        location: { latitude: 41.8003, longitude: 12.2389 },
      },
      {
        codigo: "CIA",
        cidade: "Roma",
        pais: "Itália",
        location: { latitude: 41.7999, longitude: 12.5949 },
      },
    ];
    localStorage.setItem("aeroportos", JSON.stringify(aeroportos));
  }
  // Destinos
  if (!localStorage.destinos) {
    const destinos = [
      {
        id: 1,
        cidade: "Porto",
        pais: "Portugal",
        aeroporto: "OPO",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Gastronómico",
          "Enoturismo",
        ],
        acessibilidade: [
          "Acesso Sem Degraus (variável)",
          "Transporte Acessível (Metro)",
        ],
      },
      {
        id: 2,
        cidade: "Lisboa",
        pais: "Portugal",
        aeroporto: "LIS",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Urbano",
          "Turismo Histórico",
          "Turismo Gastronómico",
        ],
        acessibilidade: [
          "Transporte Acessível (Metro)",
          "Elevadores Disponíveis",
          "Acesso Sem Degraus (variável)",
        ],
      },
      {
        id: 3,
        cidade: "Londres",
        pais: "Reino Unido",
        aeroporto: "LHR",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Urbano",
          "Turismo de Negócios",
          "Compras",
        ],
        acessibilidade: [
          "Transporte Acessível",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
          "Aluguer de Equipamento de Mobilidade",
        ],
      },
      {
        id: 4,
        cidade: "Londres",
        pais: "Reino Unido",
        aeroporto: "LGW",
        tiposTurismo: ["Turismo Cultural", "Turismo Urbano"],
        acessibilidade: ["Transporte Acessível", "Elevadores Disponíveis"],
      },
      {
        id: 5,
        cidade: "Londres",
        pais: "Reino Unido",
        aeroporto: "STN",
        tiposTurismo: ["Turismo Cultural", "Turismo Urbano"],
        acessibilidade: [
          "Transporte Acessível (comboio)",
          "Elevadores Disponíveis",
        ],
      },
      {
        id: 6,
        cidade: "Londres",
        pais: "Reino Unido",
        aeroporto: "LTN",
        tiposTurismo: ["Turismo Cultural", "Turismo Urbano"],
        acessibilidade: [
          "Transporte Acessível (comboio/bus)",
          "Elevadores Disponíveis",
        ],
      },
      {
        id: 7,
        cidade: "Londres",
        pais: "Reino Unido",
        aeroporto: "LCY",
        tiposTurismo: ["Turismo de Negócios", "Turismo Urbano"],
        acessibilidade: [
          "Transporte Acessível (DLR)",
          "Elevadores Disponíveis",
          "Acesso Sem Degraus",
        ],
      },
      {
        id: 8,
        cidade: "Paris",
        pais: "França",
        aeroporto: "CDG",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Gastronómico",
          "Turismo Urbano",
          "Moda",
        ],
        acessibilidade: [
          "Transporte Acessível (RER/Metro)",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 9,
        cidade: "Paris",
        pais: "França",
        aeroporto: "ORY",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Gastronómico",
          "Turismo Urbano",
        ],
        acessibilidade: [
          "Transporte Acessível (Orlyval/Bus)",
          "Elevadores Disponíveis",
        ],
      },
      {
        id: 10,
        cidade: "Paris",
        pais: "França",
        aeroporto: "BVA",
        tiposTurismo: ["Turismo Cultural", "Turismo Urbano"],
        acessibilidade: ["Transporte Acessível (Bus para Paris)"],
      },
      {
        id: 11,
        cidade: "Amesterdão",
        pais: "Países Baixos",
        aeroporto: "AMS",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Urbano",
          "Museus",
          "Ciclismo",
        ],
        acessibilidade: [
          "Transporte Acessível (excelente)",
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 12,
        cidade: "Madrid",
        pais: "Espanha",
        aeroporto: "MAD",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Gastronómico",
          "Vida Noturna",
          "Turismo Urbano",
        ],
        acessibilidade: [
          "Transporte Acessível (Metro excelente)",
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 13,
        cidade: "Roma",
        pais: "Itália",
        aeroporto: "FCO",
        tiposTurismo: [
          "Turismo Histórico",
          "Turismo Cultural",
          "Turismo Religioso",
          "Turismo Gastronómico",
        ],
        acessibilidade: [
          "Transporte Acessível (comboio/bus)",
          "Acesso Sem Degraus (desafiador)",
          "Elevadores Disponíveis (limitado)",
        ],
      },
      {
        id: 14,
        cidade: "Roma",
        pais: "Itália",
        aeroporto: "CIA",
        tiposTurismo: [
          "Turismo Histórico",
          "Turismo Cultural",
          "Turismo Religioso",
        ],
        acessibilidade: [
          "Transporte Acessível (Bus)",
          "Acesso Sem Degraus (desafiador)",
        ],
      },
    ];
    localStorage.setItem("destinos", JSON.stringify(destinos));
  }
  // Hoteis
  if (!localStorage.hoteis) {
    const hoteis = [
      {
        id: 1,
        cidade: "Porto",
        nome: "Hotel Infante Sagres",
        foto: "../img/misc/hoteis/Porto/Hotel_Carris_Porto_Ribeira/1.jpg",
        quartos: [
          {
            tipo: "Deluxe",
            camas: 1,
            capacidade: 2,
            precoNoite: 250,
            foto: "../img/misc/hoteis/Porto/Hotel_Carris_Porto_Ribeira/1.jpg",
            acessibilidade: ["Elevadores Disponíveis"],
            dataCheckin: "2025-07-03",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Ginásio", "Bar"],
            wifiGratis: true,
            descricao:
              "Quarto espaçoso com decoração clássica e vista para a cidade.",
          },
        ],
      },
      {
        id: 2,
        cidade: "Porto",
        nome: "The Yeatman Hotel",
        foto: "../img/misc/hoteis/Porto/Hotel_Carris_Porto_Ribeira/2.jpg",
        quartos: [
          {
            tipo: "Suite Superior Vista Rio",
            camas: 1,
            capacidade: 2,
            precoNoite: 450,
            foto: "../img/misc/hoteis/Porto/Hotel_Carris_Porto_Ribeira/2.jpg",
            acessibilidade: ["Acesso Sem Degraus", "Casas de Banho Adaptadas"],
            dataCheckin: "2025-07-15",
            numeroNoites: 4,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Restaurante Gourmet", "Bar"],
            wifiGratis: true,
            descricao:
              "Suite luxuosa com varanda e vista panorâmica para o Douro.",
          },
        ],
      },
      {
        id: 3,
        cidade: "Porto",
        nome: "Pestana Vintage Porto Hotel",
        foto: "../img/misc/hoteis/Porto/Pestana_Vintage_Porto_Hotel/1.jpg",
        quartos: [
          {
            tipo: "Vintage Classic",
            camas: 1,
            capacidade: 2,
            precoNoite: 280,
            foto: "../img/misc/hoteis/Porto/Pestana_Vintage_Porto_Hotel/1.jpg",
            acessibilidade: ["Elevadores Disponíveis"],
            dataCheckin: "2025-07-21",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Bar", "Restaurante", "Serviço de Quartos"],
            wifiGratis: true,
            descricao: "Quarto clássico com vista para o rio Douro.",
          },
        ],
      },
      {
        id: 4,
        cidade: "Porto",
        nome: "Hotel Carris Porto Ribeira",
        foto: "../img/misc/hoteis/Porto/Hotel_Carris_Porto_Ribeira/3.jpg",
        quartos: [
          {
            tipo: "Standard",
            camas: 1,
            capacidade: 2,
            precoNoite: 150,
            foto: "../img/misc/hoteis/Porto/Hotel_Carris_Porto_Ribeira/3.jpg",
            acessibilidade: ["Quartos Adaptados"],
            dataCheckin: "2025-07-10",
            numeroNoites: 5,
            pequenoAlmocoIncluido: true,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto confortável no centro histórico do Porto.",
          },
        ],
      },
      {
        id: 5,
        cidade: "Porto",
        nome: "Torel Avantgarde",
        foto: "../img/misc/hoteis/Porto/Torel_Avantgarde/1.jpg",
        quartos: [
          {
            tipo: "Executivo Vista Rio",
            camas: 1,
            capacidade: 2,
            precoNoite: 320,
            foto: "../img/misc/hoteis/Porto/Torel_Avantgarde/1.jpg",
            acessibilidade: ["Elevadores Disponíveis", "Acesso Sem Degraus"],
            dataCheckin: "2025-07-28",
            numeroNoites: 3,
            pequenoAlmocoIncluido: false,
            comodidades: ["Piscina", "Bar", "Estacionamento"],
            wifiGratis: true,
            descricao:
              "Quarto executivo com decoração moderna e vista para o rio.",
          },
        ],
      },
      {
        id: 6,
        cidade: "Lisboa",
        nome: "Four Seasons Hotel Ritz Lisbon",
        foto: "../img/misc/hoteis/Lisboa/Four_Seasons_Hotel_Ritz_Lisbon/1.jpg",
        quartos: [
          {
            tipo: "Quarto Premier",
            camas: 1,
            capacidade: 2,
            precoNoite: 600,
            foto: "../img/misc/hoteis/Lisboa/Four_Seasons_Hotel_Ritz_Lisbon/1.jpg",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Quartos Adaptados",
              "Casas de Banho Adaptadas",
            ],
            dataCheckin: "2025-07-05",
            numeroNoites: 4,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Ginásio", "Restaurante"],
            wifiGratis: true,
            descricao:
              "Quarto premier com varanda e vista para o parque Eduardo VII.",
          },
        ],
      },
      {
        id: 7,
        cidade: "Lisboa",
        nome: "Bairro Alto Hotel",
        foto: "../img/misc/hoteis/Lisboa/Bairro_Alto_Hotel/1.jpg",
        quartos: [
          {
            tipo: "Suite Chiado",
            camas: 1,
            capacidade: 2,
            precoNoite: 480,
            foto: "../img/misc/hoteis/Lisboa/Bairro_Alto_Hotel/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Aceita Cães-Guia/Assistência",
            ],
            dataCheckin: "2025-07-12",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Bar", "Restaurante", "Terraço"],
            wifiGratis: true,
            descricao: "Suite elegante no coração do bairro Alto.",
          },
        ],
      },
      {
        id: 8,
        cidade: "Lisboa",
        nome: "Memmo Alfama - Design Hotels",
        foto: "../img/misc/hoteis/Lisboa/Memmo_Alfama-Design_Hotels/1.jpg",
        quartos: [
          {
            tipo: "Quarto Terraço Vista Rio",
            camas: 1,
            capacidade: 2,
            precoNoite: 350,
            foto: "../img/misc/hoteis/Lisboa/Memmo_Alfama-Design_Hotels/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Acesso Sem Degraus (limitado)",
            ],
            dataCheckin: "2025-07-18",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Piscina", "Bar", "Restaurante"],
            wifiGratis: true,
            descricao: "Quarto com terraço privado e vista para o rio Tejo.",
          },
        ],
      },
      {
        id: 9,
        cidade: "Lisboa",
        nome: "Corinthia Lisbon",
        foto: "../img/misc/hoteis/Lisboa/Corinthia_Lisbon/1.jpg",
        quartos: [
          {
            tipo: "Deluxe King",
            camas: 1,
            capacidade: 2,
            precoNoite: 280,
            foto: "../img/misc/hoteis/Lisboa/Corinthia_Lisbon/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Quartos Adaptados",
              "Spa Acessível",
            ],
            dataCheckin: "2025-07-23",
            numeroNoites: 5,
            pequenoAlmocoIncluido: true,
            comodidades: ["Spa", "Piscina", "Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto deluxe com acesso ao spa e piscina interior.",
          },
        ],
      },
      {
        id: 10,
        cidade: "Lisboa",
        nome: "The Lumiares Hotel & Spa",
        foto: "../img/misc/hoteis/Lisboa/The_Lumiares_Hotel&Spa/1.jpg",
        quartos: [
          {
            tipo: "Apartamento Penthouse",
            camas: 2,
            capacidade: 4,
            precoNoite: 550,
            foto: "../img/misc/hoteis/Lisboa/The_Lumiares_Hotel&Spa/1.jpg",
            acessibilidade: ["Elevadores Disponíveis", "Acesso Sem Degraus"],
            dataCheckin: "2025-07-30",
            numeroNoites: 6,
            pequenoAlmocoIncluido: true,
            comodidades: ["Spa", "Restaurante", "Bar", "Estacionamento"],
            wifiGratis: true,
            descricao:
              "Penthouse espaçosa com cozinha equipada e vista panorâmica.",
          },
        ],
      },
      {
        id: 11,
        cidade: "Londres",
        nome: "The Savoy",
        foto: "../img/misc/hoteis/Londres/The_Savoy/1.jpg",
        quartos: [
          {
            tipo: "Edwardian Suite",
            camas: 1,
            capacidade: 2,
            precoNoite: 1200,
            foto: "../img/misc/hoteis/Londres/The_Savoy/1.jpg",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Quartos Adaptados",
              "Aceita Cães-Guia/Assistência",
            ],
            dataCheckin: "2025-07-01",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Spa", "Restaurante", "Bar", "Ginásio"],
            wifiGratis: true,
            descricao:
              "Suite edwardiana luxuosa com decoração clássica inglesa.",
          },
        ],
      },
      {
        id: 12,
        cidade: "Londres",
        nome: "The Ritz London",
        foto: "../img/misc/hoteis/Londres/The_Ritz_London/1.jpg",
        quartos: [
          {
            tipo: "Superior King",
            camas: 1,
            capacidade: 2,
            precoNoite: 800,
            foto: "../img/misc/hoteis/Londres/The_Ritz_London/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Acesso Sem Degraus (com assistência)",
            ],
            dataCheckin: "2025-07-05",
            numeroNoites: 4,
            pequenoAlmocoIncluido: true,
            comodidades: ["Restaurante", "Bar", "Spa"],
            wifiGratis: true,
            descricao: "Quarto superior com decoração tradicional inglesa.",
          },
        ],
      },
      {
        id: 13,
        cidade: "Londres",
        nome: "Shangri-La The Shard, London",
        foto: "../img/misc/hoteis/Londres/Shangri-La_The_Shard_London/1.jpg",
        quartos: [
          {
            tipo: "Quarto Premier Shard",
            camas: 1,
            capacidade: 2,
            precoNoite: 750,
            foto: "../img/misc/hoteis/Londres/Shangri-La_The_Shard_London/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Acesso Sem Degraus",
              "Quartos Adaptados",
            ],
            dataCheckin: "2025-07-08",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Bar", "Restaurante", "Piscina"],
            wifiGratis: true,
            descricao: "Quarto premier com vista panorâmica de Londres.",
          },
        ],
      },
      {
        id: 14,
        cidade: "Londres",
        nome: "The Langham, London",
        foto: "../img/misc/hoteis/Londres/The_Langham_London/1.jpg",
        quartos: [
          {
            tipo: "Executivo",
            camas: 1,
            capacidade: 2,
            precoNoite: 650,
            foto: "../img/misc/hoteis/Londres/The_Langham_London/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Acesso Sem Degraus",
              "Casas de Banho Adaptadas",
            ],
            dataCheckin: "2025-07-12",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Spa", "Ginásio", "Restaurante"],
            wifiGratis: true,
            descricao: "Quarto executivo com acesso exclusivo ao lounge.",
          },
        ],
      },
      {
        id: 15,
        cidade: "Londres",
        nome: "The Z Hotel Piccadilly",
        foto: "../img/misc/hoteis/Londres/The_Z_Hotel_Piccadilly/1.jpg",
        quartos: [
          {
            tipo: "Z Double",
            camas: 1,
            capacidade: 2,
            precoNoite: 180,
            foto: "../img/misc/hoteis/Londres/The_Z_Hotel_Piccadilly/1.jpg",
            acessibilidade: ["Elevadores Disponíveis"],
            dataCheckin: "2025-07-15",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Bar"],
            wifiGratis: true,
            descricao: "Quarto compacto e moderno no centro de Londres.",
          },
        ],
      },
      {
        id: 16,
        cidade: "Paris",
        nome: "Hôtel Plaza Athénée",
        foto: "../img/misc/hoteis/Paris/Hotel_Plaza_Athenee/1.jpg",
        quartos: [
          {
            tipo: "Suite Eiffel Signature",
            camas: 1,
            capacidade: 2,
            precoNoite: 2500,
            foto: "../img/misc/hoteis/Paris/Hotel_Plaza_Athenee/1.jpg",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Quartos Adaptados",
            ],
            dataCheckin: "2025-07-01",
            numeroNoites: 5,
            pequenoAlmocoIncluido: true,
            comodidades: ["Spa", "Restaurante", "Bar", "Piscina"],
            wifiGratis: true,
            descricao:
              "Suite signature com vista deslumbrante para a Torre Eiffel.",
          },
        ],
      },
      {
        id: 17,
        cidade: "Paris",
        nome: "Le Bristol Paris",
        foto: "../img/misc/hoteis/Paris/Le_Bristol_Paris/1.jpg",
        quartos: [
          {
            tipo: "Quarto Deluxe com Jardim",
            camas: 1,
            capacidade: 2,
            precoNoite: 1500,
            foto: "../img/misc/hoteis/Paris/Le_Bristol_Paris/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Aceita Cães-Guia/Assistência",
            ],
            dataCheckin: "2025-07-06",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Restaurante", "Spa", "Piscina"],
            wifiGratis: true,
            descricao: "Quarto deluxe com acesso privado ao jardim.",
          },
        ],
      },
      {
        id: 18,
        cidade: "Paris",
        nome: "Mandarin Oriental, Paris",
        foto: "../img/misc/hoteis/Paris/Mandarin_Oriental/1.jpg",
        quartos: [
          {
            tipo: "Suite Couture",
            camas: 1,
            capacidade: 2,
            precoNoite: 1800,
            foto: "../img/misc/hoteis/Paris/Mandarin_Oriental/1.jpg",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Spa Acessível",
            ],
            dataCheckin: "2025-07-10",
            numeroNoites: 4,
            pequenoAlmocoIncluido: true,
            comodidades: ["Spa", "Bar", "Restaurante", "Ginásio"],
            wifiGratis: true,
            descricao: "Suite couture com design contemporâneo francês.",
          },
        ],
      },
      {
        id: 19,
        cidade: "Paris",
        nome: "Hotel Lutetia",
        foto: "../img/misc/hoteis/Paris/Hotel_Lutetia/1.jpg",
        quartos: [
          {
            tipo: "Junior Suite Art Deco",
            camas: 1,
            capacidade: 2,
            precoNoite: 1100,
            foto: "../img/misc/hoteis/Paris/Hotel_Lutetia/1.jpg",
            acessibilidade: ["Elevadores Disponíveis", "Quartos Adaptados"],
            dataCheckin: "2025-07-14",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Bar", "Restaurante"],
            wifiGratis: true,
            descricao: "Junior suite com decoração art deco autêntica.",
          },
        ],
      },
      {
        id: 20,
        cidade: "Paris",
        nome: "Generator Paris",
        foto: "../img/misc/hoteis/Paris/Generator_Paris/1.jpg",
        quartos: [
          {
            tipo: "Cama em Dormitório Premium",
            camas: 1,
            capacidade: 1,
            precoNoite: 40,
            foto: "../img/misc/hoteis/Paris/Generator_Paris/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Ambiente Acolhedor LGBTQIA+",
            ],
            dataCheckin: "2025-07-18",
            numeroNoites: 3,
            pequenoAlmocoIncluido: false,
            comodidades: ["Bar"],
            wifiGratis: true,
            descricao: "Cama em dormitório premium com ambiente jovem.",
          },
        ],
      },
      {
        id: 21,
        cidade: "Amesterdão",
        nome: "Conservatorium Hotel",
        foto: "../img/misc/hoteis/Amsterdao/Conservatorium_Hotel/1.jpg",
        quartos: [
          {
            tipo: "Suite Duplex",
            camas: 1,
            capacidade: 2,
            precoNoite: 700,
            foto: "../img/misc/hoteis/Amsterdao/Conservatorium_Hotel/1.jpg",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Piscina Acessível",
            ],
            dataCheckin: "2025-07-02",
            numeroNoites: 4,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Bar", "Restaurante"],
            wifiGratis: true,
            descricao: "Suite duplex moderna próxima dos museus.",
          },
        ],
      },
      {
        id: 22,
        cidade: "Amesterdão",
        nome: "Pulitzer Amsterdam",
        foto: "../img/misc/hoteis/Amsterdao/Pulitzer_Amsterdam/1.jpg",
        quartos: [
          {
            tipo: "Quarto Generoso Vista Canal",
            camas: 1,
            capacidade: 2,
            precoNoite: 550,
            foto: "../img/misc/hoteis/Amsterdao/Pulitzer_Amsterdam/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Aceita Cães-Guia/Assistência",
            ],
            dataCheckin: "2025-07-07",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto generoso com vista para os canais históricos.",
          },
        ],
      },
      {
        id: 23,
        cidade: "Amesterdão",
        nome: "The Hoxton, Amsterdam",
        foto: "../img/misc/hoteis/Amsterdao/The_Hoxton/1.jpg",
        quartos: [
          {
            tipo: "Cosy Room",
            camas: 1,
            capacidade: 2,
            precoNoite: 280,
            foto: "../img/misc/hoteis/Amsterdao/The_Hoxton/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Ambiente Acolhedor LGBTQIA+",
            ],
            dataCheckin: "2025-07-11",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Bar", "Restaurante"],
            wifiGratis: true,
            descricao: "Quarto acolhedor com design contemporâneo.",
          },
        ],
      },
      {
        id: 24,
        cidade: "Amesterdão",
        nome: "Hotel V Nesplein",
        foto: "../img/misc/hoteis/Amsterdao/Hotel_V_Nesplein/1.jpg",
        quartos: [
          {
            tipo: "Loft",
            camas: 1,
            capacidade: 2,
            precoNoite: 350,
            foto: "../img/misc/hoteis/Amsterdao/Hotel_V_Nesplein/1.jpg",
            acessibilidade: ["Elevadores Disponíveis"],
            dataCheckin: "2025-07-16",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Bar"],
            wifiGratis: true,
            descricao: "Loft moderno na zona dos museus.",
          },
        ],
      },
      {
        id: 25,
        cidade: "Amesterdão",
        nome: "Flying Pig Downtown Hostel",
        foto: "../img/misc/hoteis/Amsterdao/Flying_Pig_Downtown_Hostel/1.jpg",
        quartos: [
          {
            tipo: "Cama em Dormitório Misto",
            camas: 1,
            capacidade: 1,
            precoNoite: 35,
            foto: "../img/misc/hoteis/Amsterdao/Flying_Pig_Downtown_Hostel/1.jpg",
            acessibilidade: [],
            dataCheckin: "2025-07-20",
            numeroNoites: 4,
            pequenoAlmocoIncluido: false,
            comodidades: ["Bar"],
            wifiGratis: true,
            descricao: "Cama em dormitório misto com ambiente descontraído.",
          },
        ],
      },
      {
        id: 26,
        cidade: "Madrid",
        nome: "Four Seasons Hotel Madrid",
        foto: "../img/misc/hoteis/Madrid/Four_Seasons_Hotel_Madrid/1.jpg",
        quartos: [
          {
            tipo: "Suite Real",
            camas: 1,
            capacidade: 2,
            precoNoite: 3000,
            foto: "../img/misc/hoteis/Madrid/Four_Seasons_Hotel_Madrid/1.jpg",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Quartos Adaptados",
            ],
            dataCheckin: "2025-07-05",
            numeroNoites: 4,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Ginásio", "Restaurante"],
            wifiGratis: true,
            descricao:
              "Suite real com decoração luxuosa e vista para o palácio real.",
          },
        ],
      },
      {
        id: 27,
        cidade: "Madrid",
        nome: "Hotel Regina",
        foto: "../img/misc/hoteis/Madrid/Hotel_Regina/1.jpg",
        quartos: [
          {
            tipo: "Duplo Superior",
            camas: 1,
            capacidade: 2,
            precoNoite: 180,
            foto: "../img/misc/hoteis/Madrid/Hotel_Regina/1.jpg",
            acessibilidade: ["Elevadores Disponíveis"],
            dataCheckin: "2025-07-10",
            numeroNoites: 5,
            pequenoAlmocoIncluido: true,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto duplo superior com decoração moderna.",
          },
        ],
      },
      {
        id: 28,
        cidade: "Madrid",
        nome: "Only YOU Boutique Hotel Madrid",
        foto: "../img/misc/hoteis/Madrid/Only_YOU_Boutique_Hotel/1.jpg",
        quartos: [
          {
            tipo: "Deluxe Premium",
            camas: 1,
            capacidade: 2,
            precoNoite: 350,
            foto: "../img/misc/hoteis/Madrid/Only_YOU_Boutique_Hotel/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Ambiente Acolhedor LGBTQIA+",
            ],
            dataCheckin: "2025-07-15",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto deluxe com decoração elegante e moderna.",
          },
        ],
      },
      {
        id: 29,
        cidade: "Madrid",
        nome: "Pestana Plaza Mayor Madrid",
        foto: "../img/misc/hoteis/Madrid/Pestana_Plaza_Mayor/1.jpg",
        quartos: [
          {
            tipo: "Quarto Histórico",
            camas: 1,
            capacidade: 2,
            precoNoite: 280,
            foto: "../img/misc/hoteis/Madrid/Pestana_Plaza_Mayor/1.jpg",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Piscina Acessível",
            ],
            dataCheckin: "2025-07-20",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto histórico com decoração clássica.",
          },
        ],
      },
      {
        id: 30,
        cidade: "Madrid",
        nome: "The Hat Madrid",
        foto: "../img/misc/hoteis/Madrid/The_Hat_Madrid/1.jpg",
        quartos: [
          {
            tipo: "Cama em Dormitório 4 camas",
            camas: 1,
            capacidade: 1,
            precoNoite: 30,
            foto: "../img/misc/hoteis/Madrid/The_Hat_Madrid/1.jpg",
            acessibilidade: ["Elevadores Disponíveis"],
            dataCheckin: "2025-07-25",
            numeroNoites: 3,
            pequenoAlmocoIncluido: false,
            comodidades: ["Bar"],
            wifiGratis: true,
            descricao: "Cama em dormitório com 4 camas e terraço.",
          },
        ],
      },
      {
        id: 31,
        cidade: "Roma",
        nome: "Hotel Eden - Dorchester Collection",
        foto: "../img/misc/hoteis/Roma/Hotel_Eden-Dorchester_Collection/1.jpg",
        quartos: [
          {
            tipo: "Suite Villa Medici Penthouse",
            camas: 1,
            capacidade: 2,
            precoNoite: 4000,
            foto: "../img/misc/hoteis/Roma/Hotel_Eden-Dorchester_Collection/1.jpg",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Quartos Adaptados",
            ],
            dataCheckin: "2025-07-05",
            numeroNoites: 4,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Restaurante", "Bar"],
            wifiGratis: true,
            descricao:
              "Suite penthouse com decoração luxuosa e vista para a cidade eterna.",
          },
        ],
      },
      {
        id: 32,
        cidade: "Roma",
        nome: "Hotel Artemide",
        foto: "../img/misc/hoteis/Roma/Hotel_Artemide/1.jpg",
        quartos: [
          {
            tipo: "Duplo Comfort",
            camas: 1,
            capacidade: 2,
            precoNoite: 250,
            foto: "../img/misc/hoteis/Roma/Hotel_Artemide/1.jpg",
            acessibilidade: ["Elevadores Disponíveis", "Spa Acessível"],
            dataCheckin: "2025-07-10",
            numeroNoites: 5,
            pequenoAlmocoIncluido: true,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto duplo confortável com decoração moderna.",
          },
        ],
      },
      {
        id: 33,
        cidade: "Roma",
        nome: "St. Regis Rome",
        foto: "../img/misc/hoteis/Roma/St_Regis_Rome/1.jpg",
        quartos: [
          {
            tipo: "Imperial Room",
            camas: 1,
            capacidade: 2,
            precoNoite: 700,
            foto: "../img/misc/hoteis/Roma/St_Regis_Rome/1.jpg",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Aceita Cães-Guia/Assistência",
            ],
            dataCheckin: "2025-07-15",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Restaurante", "Bar"],
            wifiGratis: true,
            descricao:
              "Quarto imperial com decoração luxuosa e vista para a cidade.",
          },
        ],
      },
      {
        id: 34,
        cidade: "Roma",
        nome: "Hotel Vilòn - Small Luxury Hotels of the World",
        foto: "../img/misc/hoteis/Roma/Hotel_Vilon/1.jpg",
        quartos: [
          {
            tipo: "Vilòn Charming",
            camas: 1,
            capacidade: 2,
            precoNoite: 550,
            foto: "../img/misc/hoteis/Roma/Hotel_Vilon/1.jpg",
            acessibilidade: ["Elevadores Disponíveis", "Pátio Acessível"],
            dataCheckin: "2025-07-20",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto encantador com acesso a pátio privado.",
          },
        ],
      },
      {
        id: 35,
        cidade: "Roma",
        nome: "The RomeHello Hostel",
        foto: "../img/misc/hoteis/Roma/The_RomeHello_Hostel/1.jpg",
        quartos: [
          {
            tipo: "Cama em Dormitório Feminino",
            camas: 1,
            capacidade: 1,
            precoNoite: 38,
            foto: "../img/misc/hoteis/Roma/The_RomeHello_Hostel/1.jpg",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Acesso Sem Degraus (limitado)",
            ],
            dataCheckin: "2025-07-30",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Bar"],
            wifiGratis: true,
            descricao:
              "Cama em dormitório feminino próximo do centro histórico.",
          },
        ],
      },
    ];
    localStorage.setItem("hoteis", JSON.stringify(hoteis));
  }
  // Atividades
  if (!localStorage.atividades) {
    const atividades = [
      {
        id: 1,
        destinoId: 1,
        tipoTurismo: "Enoturismo",
        nome: "Cruzeiro das 6 Pontes e Visita a Cave",
        foto: "../img/misc/atividades/Porto/Cruzeiro_das_6_Pontes_e_Visita_a_Cave/1.jpg",
        descricao:
          "Combine um cruzeiro panorâmico com uma prova de Vinho do Porto.",
        acessibilidade: [
          "Acesso Sem Degraus (barco variável)",
          "Elevadores Disponíveis (algumas caves)",
        ],
      },
      {
        id: 2,
        destinoId: 1,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita Guiada à Torre dos Clérigos",
        foto: "../img/misc/atividades/Porto/Visita_Guiada_à_Torre_dos_Clérigos/1.jpg",
        descricao:
          "Suba à torre e aprecie vistas panorâmicas do Porto.",
        acessibilidade: [
          "Acesso Sem Degraus (limitado)",
          "Escadas",
        ],
      },
      {
        id: 3,
        destinoId: 1,
        tipoTurismo: "Turismo Cultural",
        nome: "Entrada na Livraria Lello",
        foto: "../img/misc/atividades/Porto/Entrada_na_Livraria_Lello/1.jpg",
        descricao: "Visite uma das livrarias mais famosas do mundo.",
        acessibilidade: ["Acesso Sem Degraus (limitado)", "Multidões"],
      },
      {
        id: 4,
        destinoId: 1,
        tipoTurismo: "Turismo Urbano",
        nome: "Passeio de Tuk Tuk pela Ribeira e Centro Histórico",
        foto: "../img/misc/atividades/Porto/Passeio_de_Tuk_Tuk_pela_Ribeira_e_Centro_Histórico/1.jpg",
        descricao:
          "Descubra os cantos pitorescos da cidade de forma divertida.",
        acessibilidade: ["Transporte Acessível (variável)"],
      },
      {
        id: 5,
        destinoId: 1,
        tipoTurismo: "Turismo Gastronómico",
        nome: "Workshop de Pastel de Nata no Porto",
        foto: "../img/misc/atividades/Porto/Workshop_de_Pastel_de_Nata_no_Porto/1.jpg",
        descricao: "Aprenda a fazer o famoso doce português.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Opções Alimentares Específicas (informar)",
        ],
      },
      {
        id: 6,
        destinoId: 2,
        tipoTurismo: "Turismo Histórico",
        nome: "Visita Guiada ao Mosteiro dos Jerónimos",
        foto: "../img/misc/atividades/Lisboa/Visita_Guiada_ao_Mosteiro_dos_Jerónimos/1.jpg",
        descricao: "Explore a obra-prima do estilo manuelino.",
        acessibilidade: [
          "Acesso Sem Degraus (parcial)",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 7,
        destinoId: 2,
        tipoTurismo: "Turismo Urbano",
        nome: "Tour a Pé por Alfama e Castelo",
        foto: "../img/misc/atividades/Lisboa/Tour_a_Pé_por_Alfama_e_Castelo/1.jpg",
        descricao:
          "Perca-se nas ruas estreitas e descubra vistas deslumbrantes.",
        acessibilidade: [
          "Acesso Sem Degraus (muito limitado)",
          "Percurso com subidas",
        ],
      },
      {
        id: 8,
        destinoId: 2,
        tipoTurismo: "Turismo Cultural",
        nome: "Espetáculo de Fado com Jantar",
        foto: "../img/misc/atividades/Lisboa/Espetáculo_de_Fado_com_Jantar/1.jpg",
        descricao: "Viva a emoção da música tradicional portuguesa.",
        acessibilidade: [
          "Acesso Sem Degraus (depende do local)",
          "Ambientes Sensoriais Calmos (relativamente)",
        ],
      },
      {
        id: 9,
        destinoId: 2,
        tipoTurismo: "Turismo Gastronómico",
        nome: "Tour de Elétrico 28 com Prova de Pastéis de Belém",
        foto: "../img/misc/atividades/Lisboa/Tour_de_Elétrico_28_com_Prova_de_Pastéis_de_Belém/1.jpg",
        descricao: "Combine o icónico elétrico com o doce mais famoso.",
        acessibilidade: ["Transporte Acessível (muito limitado no elétrico)"],
      },
      {
        id: 10,
        destinoId: 2,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita ao Museu Nacional do Azulejo",
        foto: "../img/misc/atividades/Lisboa/Visita_ao_Museu_Nacional_do_Azulejo/1.jpg",
        descricao: "Descubra a história e a arte do azulejo português.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 11,
        destinoId: 3,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita à Torre de Londres e Joias da Coroa",
        foto: "../img/misc/atividades/Londres/Visita_à_Torre_de_Londres_e_Joias_da_Coroa/1.jpg",
        descricao: "Explore a história e veja as famosas joias.",
        acessibilidade: [
          "Acesso Sem Degraus (limitado)",
          "Aluguer de Equipamento de Mobilidade",
          "Guia Áudio",
        ],
      },
      {
        id: 12,
        destinoId: 4,
        tipoTurismo: "Turismo Urbano",
        nome: "Passeio no London Eye com Vista Panorâmica",
        foto: "../img/misc/atividades/Londres/Passeio_no_London_Eye_com_Vista_Panorâmica/1.jpg",
        descricao: "Desfrute de vistas de 360 graus sobre a cidade.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas (próximo)",
        ],
      },
      {
        id: 13,
        destinoId: 5,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita ao British Museum",
        foto: "../img/misc/atividades/Londres/Visita_ao_British_Museum/1.jpg",
        descricao: "Descubra tesouros de todo o mundo.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
          "Informação em Braille/Áudio (limitado)",
        ],
      },
      {
        id: 14,
        destinoId: 6,
        tipoTurismo: "Turismo Urbano",
        nome: "Tour pelos Mercados de Londres (Borough, Camden)",
        foto: "../img/misc/atividades/Londres/Tour_pelos_Mercados_de_Londres_(Borough_Camden)/1.jpg",
        descricao: "Experimente a diversidade gastronómica e cultural.",
        acessibilidade: ["Acesso Sem Degraus (variável)", "Multidões"],
      },
      {
        id: 15,
        destinoId: 7,
        tipoTurismo: "Turismo Cultural",
        nome: "Bilhete para Musical no West End",
        foto: "../img/misc/atividades/Londres/Bilhete_para_Musical_no_West_End/1.jpg",
        descricao: "Assista a um espetáculo de renome mundial.",
        acessibilidade: [
          "Acesso Sem Degraus (verificar teatro)",
          "Casas de Banho Adaptadas (verificar teatro)",
        ],
      },
      {
        id: 16,
        destinoId: 8,
        tipoTurismo: "Turismo Cultural",
        nome: "Bilhete Sem Fila para o Museu do Louvre",
        foto: "../img/misc/atividades/Paris/Bilhete_Sem_Fila_para_o_Museu_do_Louvre/1.jpg",
        descricao: "Evite as filas e veja obras-primas como a Mona Lisa.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
          "Aluguer de Equipamento de Mobilidade",
        ],
      },
      {
        id: 17,
        destinoId: 9,
        tipoTurismo: "Turismo Urbano",
        nome: "Subida ao 2º Andar ou Topo da Torre Eiffel",
        foto: "../img/misc/atividades/Paris/Subida_ao_2º_Andar_ou_Topo_da_Torre_Eiffel/1.jpg",
        descricao: "A vista icónica de Paris.",
        acessibilidade: [
          "Elevadores Disponíveis",
          "Acesso Sem Degraus (limitado na base)",
        ],
      },
      {
        id: 18,
        destinoId: 10,
        tipoTurismo: "Turismo Cultural",
        nome: "Cruzeiro no Sena com Guia Áudio",
        foto: "../img/misc/atividades/Paris/Cruzeiro_no_Sena_com_Guia_Áudio/1.jpg",
        descricao: "Veja os monumentos parisienses a partir do rio.",
        acessibilidade: ["Acesso Sem Degraus (barco variável)", "Guia Áudio"],
      },
      {
        id: 19,
        destinoId: 8,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita ao Museu d'Orsay",
        foto: "../img/misc/atividades/Paris/Visita_ao_Museu_d'Orsay/1.jpg",
        descricao: "Explore a arte impressionista e pós-impressionista.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 20,
        destinoId: 9,
        tipoTurismo: "Turismo Urbano",
        nome: "Passeio Guiado por Montmartre e Sacré-Cœur",
        foto: "../img/misc/atividades/Paris/Passeio_Guiado_por_Montmartre_e_Sacré-Cœur/1.jpg",
        descricao: "Descubra o bairro dos artistas e a basílica.",
        acessibilidade: [
          "Acesso Sem Degraus (muito limitado)",
          "Percurso com subidas",
        ],
      },
      {
        id: 21,
        destinoId: 11,
        tipoTurismo: "Turismo Histórico",
        nome: "Bilhete para a Casa de Anne Frank",
        foto: "../img/misc/atividades/Amesterdão/Bilhete_para_a_Casa_de_Anne_Frank/1.jpg",
        descricao: "Visite o anexo secreto e conheça a história.",
        acessibilidade: [
          "Acesso Sem Degraus (limitado)",
          "Espaços apertados",
          "Necessário reservar com antecedência",
        ],
      },
      {
        id: 22,
        destinoId: 11,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita ao Rijksmuseum com Obras de Rembrandt",
        foto: "../img/misc/atividades/Amesterdão/Visita_ao_Rijksmuseum_com_Obras_de_Rembrandt/1.jpg",
        descricao: "Veja a 'Ronda da Noite' e outros mestres holandeses.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
          "Guia Áudio",
        ],
      },
      {
        id: 23,
        destinoId: 11,
        tipoTurismo: "Turismo Cultural",
        nome: "Passeio de Barco Clássico pelos Canais",
        foto: "../img/misc/atividades/Amesterdão/Passeio_de_Barco_Clássico_pelos_Canais/1.jpg",
        descricao: "Descubra a cidade a partir da água.",
        acessibilidade: ["Acesso Sem Degraus (barco variável)", "Guia Áudio"],
      },
      {
        id: 24,
        destinoId: 11,
        tipoTurismo: "Turismo Gastronómico",
        nome: "Tour de Comida de Rua e Mercados",
        foto: "../img/misc/atividades/Amesterdão/Tour_de_Comida_de_Rua_e_Mercados/1.jpg",
        descricao: "Prove stroopwafels, arenque e queijos locais.",
        acessibilidade: [
          "Percurso pedestre",
          "Opções Alimentares Específicas (limitado)",
        ],
      },
      {
        id: 25,
        destinoId: 11,
        tipoTurismo: "Turismo Urbano",
        nome: "Aluguer de Bicicleta por um Dia",
        foto: "../img/misc/atividades/Amesterdão/Aluguer_de_Bicicleta_por_um_Dia/1.jpg",
        descricao: "Explore Amesterdão como um local.",
        acessibilidade: ["Requer capacidade física"],
      },
      {
        id: 26,
        destinoId: 12,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita Guiada ao Museu do Prado",
        foto: "../img/misc/atividades/Madrid/Visita_Guiada_ao_Museu_do_Prado/1.jpg",
        descricao: "Conheça as obras-primas de Goya, Velázquez e El Greco.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
          "Aluguer de Equipamento de Mobilidade",
        ],
      },
      {
        id: 27,
        destinoId: 12,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita ao Palácio Real e Jardins de Sabatini",
        foto: "../img/misc/atividades/Madrid/Visita_ao_Palácio_Royal_e_Jardins_de_Sabatini/1.jpg",
        descricao: "Explore a residência oficial da monarquia espanhola.",
        acessibilidade: [
          "Acesso Sem Degraus (parcial)",
          "Elevadores Disponíveis",
        ],
      },
      {
        id: 28,
        destinoId: 12,
        tipoTurismo: "Turismo Urbano",
        nome: "Passeio pelo Parque del Retiro e Barco no Lago",
        foto: "../img/misc/atividades/Madrid/Passeio_pelo_Parque_del_Retiro_e_Barco_no_Lago/1.jpg",
        descricao: "Relaxe no pulmão verde de Madrid.",
        acessibilidade: ["Acesso Sem Degraus", "Casas de Banho Adaptadas"],
      },
      {
        id: 29,
        destinoId: 12,
        tipoTurismo: "Turismo Gastronómico",
        nome: "Tour de Tapas pelos Bairros Históricos",
        foto: "../img/misc/atividades/Madrid/Tour_de_Tapas_pelos_Bairros_Históricos/1.jpg",
        descricao: "Descubra os sabores autênticos de Madrid.",
        acessibilidade: [
          "Percurso pedestre",
          "Opções Alimentares Específicas (informar)",
        ],
      },
      {
        id: 30,
        destinoId: 12,
        tipoTurismo: "Turismo Cultural",
        nome: "Espetáculo de Flamenco Tradicional",
        foto: "../img/misc/atividades/Madrid/Espetáculo_de_Flamenco_Tradicional/1.jpg",
        descricao: "Sinta a paixão e a arte do flamenco.",
        acessibilidade: [
          "Acesso Sem Degraus (verificar local)",
          "Ambiente com música alta",
        ],
      },
      {
        id: 31,
        destinoId: 13,
        tipoTurismo: "Turismo Histórico",
        nome: "Visita Guiada ao Coliseu, Fórum Romano e Monte Palatino",
        foto: "../img/misc/atividades/Roma/Visita_Guiada_ao_Coliseu_Fórum_Romano_e_Monte_Palatino/1.jpg",
        descricao: "Viaje no tempo até à Roma Antiga.",
        acessibilidade: [
          "Acesso Sem Degraus (limitado, terreno irregular)",
          "Elevadores Disponíveis (Coliseu)",
        ],
      },
      {
        id: 32,
        destinoId: 14,
        tipoTurismo: "Turismo Religioso",
        nome: "Visita aos Museus Vaticanos, Capela Sistina e Basílica de São Pedro",
        foto: "../img/misc/atividades/Roma/Visita_aos_Museus_Vaticanos_Capela_Sistina_e_Basílica_de_São_Pedro/1.jpg",
        descricao: "Explore os tesouros artísticos e religiosos do Vaticano.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Aluguer de Equipamento de Mobilidade",
        ],
      },
      {
        id: 33,
        destinoId: 13,
        tipoTurismo: "Turismo Urbano",
        nome: "Passeio pela Fontana di Trevi e Panteão",
        foto: "../img/misc/atividades/Roma/Passeio_pela_Fontana_di_Trevi_e_Panteão/1.jpg",
        descricao: "Visite dois dos monumentos mais icónicos de Roma.",
        acessibilidade: ["Acesso Sem Degraus (Panteão)", "Multidões"],
      },
      {
        id: 34,
        destinoId: 14,
        tipoTurismo: "Turismo Gastronómico",
        nome: "Aula de Culinária: Pasta e Tiramisu",
        foto: "../img/misc/atividades/Roma/Aula_de_Culinária_Pasta_e_Tiramisu/1.jpg",
        descricao: "Aprenda a cozinhar pratos italianos clássicos.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Opções Alimentares Específicas (informar)",
        ],
      },
      {
        id: 35,
        destinoId: 13,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita à Galeria Borghese e Jardins",
        foto: "../img/misc/atividades/Roma/Visita_à_Galeria_Borghese_e_Jardins/1.jpg",
        descricao: "Admire esculturas de Bernini e pinturas de Caravaggio.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Necessário reservar com antecedência",
        ],
      },
    ];
    localStorage.setItem("atividades", JSON.stringify(atividades));
  }
  // Tipos de Turismo
  if (!localStorage.tiposTurismo) {
    const tiposTurismo = [
      "Turismo religioso",
      "Turismo cultural",
      "Ecoturismo",
      "Turismo rural",
      "Turismo gastronómico",
      "Turismo de Sol e Praia",
      "Turismo de negócios",
      "Saúde e Bem-Estar",
      "Turismo Urbano",
    ];
    localStorage.setItem("tiposTurismo", JSON.stringify(tiposTurismo));
  }
  // Acessibilidade
  if (!localStorage.acessibilidade) {
    const acessibilidade = [
      "Acesso Sem Degraus",
      "Elevadores Disponíveis",
      "Casas de Banho Adaptadas",
      "Quartos Adaptados",
      "Transporte Acessível",
      "Informação em Braille/Áudio",
      "Alarmes Visuais/Vibratórios",
      "Aceita Cães-Guia/Assistência",
      "Ambientes Sensoriais Calmos",
      "Opções Alimentares Específicas",
      "Comunicação Visual/Simplificada",
      "Aluguer de Equipamento de Mobilidade",
      "Superfícies Táteis/Guia",
      "Proximidade a Serviços Médicos",
      "Ambiente Acolhedor LGBTQIA+",
      "Alojamento Inclusivo Declarado",
      "Negócios de Proprietários de Minorias",
      "Casas de Banho Neutras em Género",
    ];
    localStorage.setItem("acessibilidade", JSON.stringify(acessibilidade));
  }
  // Viagens
  if (!localStorage.viagens) {
    const viagens = [
      {
        numeroVoo: "TP2456",
        origem: "OPO - Porto",
        destino: "Lisboa",
        companhia: "TAP",
        partida: "01/07/2025 08:15",
        chegada: "01/07/2025 09:10",
        direto: "S",
        custo: 75,
        imagem: "../img/misc/destinos/Lisboa/1.jpg",
        dataVolta: "05/07/2025 08:15",
        turismo: ["Turismocultural", "Turismogastronomico", "TurismoUrbano"],
      },
      {
        numeroVoo: "TP2457",
        origem: "LIS - Lisboa",
        destino: "Porto",
        companhia: "TAP",
        partida: "03/07/2025 10:00",
        chegada: "03/07/2025 10:55",
        direto: "S",
        custo: 80,
        imagem: "../img/misc/destinos/Porto/1.jpg",
        dataVolta: "08/07/2025 10:00",
        turismo: ["Turismocultural", "Turismoreligioso", "TurismoUrbano"],
      },
      {
        numeroVoo: "BA1001",
        origem: "OPO - Porto",
        destino: "Londres",
        companhia: "British Airways",
        partida: "05/07/2025 06:30",
        chegada: "05/07/2025 08:30",
        direto: "S",
        custo: 200,
        imagem: "../img/misc/destinos/Londres/1.jpg",
        dataVolta: "10/07/2025 06:30",
        turismo: ["TurismoUrbano", "Turismocultural", "Turismodenegocios"],
      },
      {
        numeroVoo: "BA1002",
        origem: "LHR - Londres",
        destino: "Porto",
        companhia: "British Airways",
        partida: "07/07/2025 14:00",
        chegada: "07/07/2025 16:00",
        direto: "S",
        custo: 210,
        imagem: "../img/misc/destinos/Porto/2.jpg",
        dataVolta: "12/07/2025 14:00",
        turismo: ["Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "AF150",
        origem: "LIS - Lisboa",
        destino: "Paris",
        companhia: "Air France",
        partida: "09/07/2025 09:45",
        chegada: "09/07/2025 12:15",
        direto: "S",
        custo: 180,
        imagem: "../img/misc/destinos/Paris/1.jpg",
        dataVolta: "14/07/2025 09:45",
        turismo: ["TurismoUrbano", "Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "AF151",
        origem: "CDG - Paris",
        destino: "Lisboa",
        companhia: "Air France",
        partida: "11/07/2025 15:30",
        chegada: "11/07/2025 17:50",
        direto: "S",
        custo: 190,
        imagem: "../img/misc/destinos/Lisboa/2.jpg",
        dataVolta: "16/07/2025 15:30",
        turismo: ["TurismodeSolePraia", "TurismoUrbano"],
      },
      {
        numeroVoo: "KL110",
        origem: "AMS - Amesterdão",
        destino: "Roma",
        companhia: "KLM",
        partida: "13/07/2025 07:00",
        chegada: "13/07/2025 09:00",
        direto: "S",
        custo: 220,
        imagem: "../img/misc/destinos/Roma/1.jpg",
        dataVolta: "18/07/2025 07:00",
        turismo: ["Turismoreligioso", "Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "KL111",
        origem: "AMS - Amesterdão",
        destino: "Roma",
        companhia: "KLM",
        partida: "15/07/2025 12:00",
        chegada: "15/07/2025 14:30",
        direto: "S",
        custo: 230,
        imagem: "../img/misc/destinos/Roma/2.jpg",
        dataVolta: "20/07/2025 12:00",
        turismo: ["Turismoreligioso", "Turismogastronomico"],
      },
      {
        numeroVoo: "FR300",
        origem: "STN - Londres",
        destino: "Lisboa",
        companhia: "Ryanair",
        partida: "17/07/2025 06:50",
        chegada: "17/07/2025 10:30",
        direto: "N",
        custo: 90,
        imagem: "../img/misc/destinos/Lisboa/3.jpg",
        dataVolta: "22/07/2025 06:50",
        turismo: ["TurismodeSolePraia", "Turismocultural"],
      },
      {
        numeroVoo: "FR301",
        origem: "LIS - Lisboa",
        destino: "Londres",
        companhia: "Ryanair",
        partida: "19/07/2025 11:20",
        chegada: "19/07/2025 13:00",
        direto: "N",
        custo: 95,
        imagem: "../img/misc/destinos/Londres/2.jpg",
        dataVolta: "24/07/2025 11:20",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "BA200",
        origem: "LGW - Londres",
        destino: "Madrid",
        companhia: "British Airways",
        partida: "21/07/2025 07:15",
        chegada: "21/07/2025 10:30",
        direto: "S",
        custo: 150,
        imagem: "../img/misc/destinos/Madrid/1.jpg",
        dataVolta: "26/07/2025 07:15",
        turismo: ["Turismocultural", "Turismogastronomico", "TurismoUrbano"],
      },
      {
        numeroVoo: "BA201",
        origem: "MAD - Madrid",
        destino: "Londres",
        companhia: "British Airways",
        partida: "23/07/2025 12:00",
        chegada: "23/07/2025 15:00",
        direto: "S",
        custo: 155,
        imagem: "../img/misc/destinos/Londres/3.jpg",
        dataVolta: "28/07/2025 12:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "U2789",
        origem: "LTN - Londres",
        destino: "Amesterdão",
        companhia: "EasyJet",
        partida: "25/07/2025 08:00",
        chegada: "25/07/2025 11:10",
        direto: "S",
        custo: 120,
        imagem: "../img/misc/destinos/Amesterdao/1.jpg",
        dataVolta: "30/07/2025 08:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "U2790",
        origem: "AMS - Amesterdão",
        destino: "Londres",
        companhia: "EasyJet",
        partida: "27/07/2025 18:20",
        chegada: "27/07/2025 21:30",
        direto: "S",
        custo: 125,
        imagem: "../img/misc/destinos/Londres/1.jpg",
        dataVolta: "01/08/2025 18:20",
        turismo: ["TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "AF2000",
        origem: "ORY - Paris",
        destino: "Londres",
        companhia: "Air France",
        partida: "29/07/2025 09:00",
        chegada: "29/07/2025 10:15",
        direto: "N",
        custo: 110,
        imagem: "../img/misc/destinos/Londres/2.jpg",
        dataVolta: "03/08/2025 09:00",
        turismo: ["TurismoUrbano", "Turismocultural"],
      },
      {
        numeroVoo: "FR305",
        origem: "STN - Londres",
        destino: "Paris",
        companhia: "Ryanair",
        partida: "02/08/2025 14:00",
        chegada: "02/08/2025 18:00",
        direto: "N",
        custo: 95,
        imagem: "../img/misc/destinos/Paris/2.jpg",
        dataVolta: "07/08/2025 14:00",
        turismo: ["TurismoUrbano", "Turismogastronomico"],
      },
      {
        numeroVoo: "AF2010",
        origem: "CDG - Paris",
        destino: "Paris",
        companhia: "Air France",
        partida: "04/08/2025 10:00",
        chegada: "04/08/2025 10:45",
        direto: "S",
        custo: 100,
        imagem: "../img/misc/destinos/Paris/3.jpg",
        dataVolta: "09/08/2025 10:00",
        turismo: ["TurismoUrbano", "Turismocultural"],
      },
      {
        numeroVoo: "AF2011",
        origem: "BVA - Paris",
        destino: "Paris",
        companhia: "Air France",
        partida: "06/08/2025 12:00",
        chegada: "06/08/2025 12:45",
        direto: "S",
        custo: 100,
        imagem: "../img/misc/destinos/Paris/1.jpg",
        dataVolta: "11/08/2025 12:00",
        turismo: ["TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "KL115",
        origem: "LIS - Lisboa",
        destino: "Amesterdão",
        companhia: "KLM",
        partida: "08/08/2025 07:00",
        chegada: "08/08/2025 09:30",
        direto: "S",
        custo: 170,
        imagem: "../img/misc/destinos/Amesterdao/2.jpg",
        dataVolta: "13/08/2025 07:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "KL116",
        origem: "AMS - Amesterdão",
        destino: "Lisboa",
        companhia: "KLM",
        partida: "10/08/2025 13:00",
        chegada: "10/08/2025 15:30",
        direto: "S",
        custo: 175,
        imagem: "../img/misc/destinos/Lisboa/1.jpg",
        dataVolta: "15/08/2025 13:00",
        turismo: ["TurismodeSolePraia", "Turismogastronomico"],
      },
      {
        numeroVoo: "AZ320",
        origem: "CIA - Roma",
        destino: "Madrid",
        companhia: "Alitalia",
        partida: "12/08/2025 06:30",
        chegada: "12/08/2025 08:45",
        direto: "N",
        custo: 200,
        imagem: "../img/misc/destinos/Madrid/2.jpg",
        dataVolta: "17/08/2025 06:30",
        turismo: ["Turismocultural", "Turismogastronomico", "TurismoUrbano"],
      },
      {
        numeroVoo: "AZ321",
        origem: "MAD - Madrid",
        destino: "Roma",
        companhia: "Alitalia",
        partida: "14/08/2025 17:00",
        chegada: "14/08/2025 19:15",
        direto: "N",
        custo: 205,
        imagem: "../img/misc/destinos/Roma/3.jpg",
        dataVolta: "19/08/2025 17:00",
        turismo: ["Turismoreligioso", "Turismocultural"],
      },
      {
        numeroVoo: "BA550",
        origem: "LGW - Londres",
        destino: "Londres",
        companhia: "British Airways",
        partida: "16/08/2025 09:00",
        chegada: "16/08/2025 10:00",
        direto: "S",
        custo: 80,
        imagem: "../img/misc/destinos/Londres/1.jpg",
        dataVolta: "21/08/2025 09:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "BA551",
        origem: "LCY - Londres",
        destino: "Londres",
        companhia: "British Airways",
        partida: "18/08/2025 12:30",
        chegada: "18/08/2025 13:30",
        direto: "S",
        custo: 85,
        imagem: "../img/misc/destinos/Londres/2.jpg",
        dataVolta: "23/08/2025 12:30",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "TP300",
        origem: "LHR - Londres",
        destino: "Lisboa",
        companhia: "TAP",
        partida: "20/08/2025 08:00",
        chegada: "20/08/2025 11:00",
        direto: "S",
        custo: 160,
        imagem: "../img/misc/destinos/Lisboa/3.jpg",
        dataVolta: "25/08/2025 08:00",
        turismo: [
          "TurismodeSolePraia",
          "Turismocultural",
          "Turismogastronomico",
        ],
      },
      {
        numeroVoo: "TP301",
        origem: "LIS - Lisboa",
        destino: "Londres",
        companhia: "TAP",
        partida: "22/08/2025 14:00",
        chegada: "22/08/2025 17:00",
        direto: "S",
        custo: 165,
        imagem: "../img/misc/destinos/Londres/3.jpg",
        dataVolta: "27/08/2025 14:00",
        turismo: ["Turismodenegocios", "TurismoUrbano", "Turismocultural"],
      },
      {
        numeroVoo: "VY821",
        origem: "STN - Londres",
        destino: "Madrid",
        companhia: "Vueling",
        partida: "24/08/2025 07:15",
        chegada: "24/08/2025 10:15",
        direto: "N",
        custo: 120,
        imagem: "../img/misc/destinos/Madrid/1.jpg",
        dataVolta: "29/08/2025 07:15",
        turismo: ["Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "VY822",
        origem: "MAD - Madrid",
        destino: "Londres",
        companhia: "Vueling",
        partida: "26/08/2025 12:00",
        chegada: "26/08/2025 15:00",
        direto: "N",
        custo: 125,
        imagem: "../img/misc/destinos/Londres/2.jpg",
        dataVolta: "31/08/2025 12:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "SN100",
        origem: "BVA - Paris",
        destino: "Amesterdão",
        companhia: "Brussels Airlines",
        partida: "01/09/2025 09:00",
        chegada: "01/09/2025 10:30",
        direto: "S",
        custo: 95,
        imagem: "../img/misc/destinos/Porto/1.jpg", // fallback image
        dataVolta: "06/09/2025 09:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "SN101",
        origem: "AMS - Amesterdão",
        destino: "Paris",
        companhia: "Brussels Airlines",
        partida: "03/09/2025 12:00",
        chegada: "03/09/2025 13:30",
        direto: "S",
        custo: 100,
        imagem: "../img/misc/destinos/Paris/2.jpg",
        dataVolta: "08/09/2025 12:00",
        turismo: ["TurismoUrbano", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1001",
        origem: "AMS - Amesterdão",
        destino: "Londres",
        companhia: "TAP",
        partida: "05/09/2025 06:00",
        chegada: "05/09/2025 08:00",
        direto: "S",
        custo: 150,
        imagem: "../img/misc/destinos/Londres/1.jpg",
        dataVolta: "10/09/2025 06:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "OP1002",
        origem: "CDG - Paris",
        destino: "Londres",
        companhia: "Ryanair",
        partida: "07/09/2025 09:30",
        chegada: "07/09/2025 11:45",
        direto: "N",
        custo: 85,
        imagem: "../img/misc/destinos/Londres/2.jpg",
        dataVolta: "12/09/2025 09:30",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "OP1003",
        origem: "ORY - Paris",
        destino: "Londres",
        companhia: "EasyJet",
        partida: "09/09/2025 07:15",
        chegada: "09/09/2025 09:30",
        direto: "S",
        custo: 120,
        imagem: "../img/misc/destinos/Londres/3.jpg",
        dataVolta: "14/09/2025 07:15",
        turismo: ["TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1004",
        origem: "FCO - Roma",
        destino: "Londres",
        companhia: "TAP",
        partida: "11/09/2025 12:00",
        chegada: "11/09/2025 14:15",
        direto: "S",
        custo: 140,
        imagem: "../img/misc/destinos/Londres/1.jpg",
        dataVolta: "16/09/2025 12:00",
        turismo: ["Turismocultural", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1005",
        origem: "CIA - Roma",
        destino: "Paris",
        companhia: "Air France",
        partida: "13/09/2025 08:45",
        chegada: "13/09/2025 11:10",
        direto: "N",
        custo: 160,
        imagem: "../img/misc/destinos/Paris/3.jpg",
        dataVolta: "18/09/2025 08:45",
        turismo: ["Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1006",
        origem: "LCY - Londres",
        destino: "Paris",
        companhia: "KLM",
        partida: "15/09/2025 13:00",
        chegada: "15/09/2025 15:05",
        direto: "S",
        custo: 170,
        imagem: "../img/misc/destinos/Paris/1.jpg",
        dataVolta: "20/09/2025 13:00",
        turismo: ["TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1007",
        origem: "BVA - Paris",
        destino: "Paris",
        companhia: "Brussels Airlines",
        partida: "17/09/2025 06:30",
        chegada: "17/09/2025 08:00",
        direto: "S",
        custo: 130,
        imagem: "../img/misc/destinos/Paris/2.jpg",
        dataVolta: "22/09/2025 06:30",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "OP1008",
        origem: "CDG - Paris",
        destino: "Amesterdão",
        companhia: "Ryanair",
        partida: "19/09/2025 10:00",
        chegada: "19/09/2025 13:00",
        direto: "N",
        custo: 95,
        imagem: "../img/misc/destinos/Amesterdao/1.jpg",
        dataVolta: "24/09/2025 10:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "OP1009",
        origem: "AMS - Amesterdão",
        destino: "Madrid",
        companhia: "TAP",
        partida: "21/09/2025 07:00",
        chegada: "21/09/2025 09:15",
        direto: "S",
        custo: 145,
        imagem: "../img/misc/destinos/Madrid/2.jpg",
        dataVolta: "26/09/2025 07:00",
        turismo: ["Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1010",
        origem: "MAD - Madrid",
        destino: "Roma",
        companhia: "Alitalia",
        partida: "23/09/2025 11:45",
        chegada: "23/09/2025 13:50",
        direto: "N",
        custo: 180,
        imagem: "../img/misc/destinos/Roma/3.jpg",
        dataVolta: "28/09/2025 11:45",
        turismo: ["Turismoreligioso", "Turismocultural"],
      },
      {
        numeroVoo: "OP1011",
        origem: "LGW - Londres",
        destino: "Roma",
        companhia: "British Airways",
        partida: "25/09/2025 06:15",
        chegada: "25/09/2025 08:45",
        direto: "S",
        custo: 155,
        imagem: "../img/misc/destinos/Roma/1.jpg",
        dataVolta: "30/09/2025 06:15",
        turismo: ["Turismoreligioso", "Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1012",
        origem: "CDG - Paris",
        destino: "Roma",
        companhia: "EasyJet",
        partida: "27/09/2025 10:30",
        chegada: "27/09/2025 12:00",
        direto: "S",
        custo: 125,
        imagem: "../img/misc/destinos/Roma/2.jpg",
        dataVolta: "02/10/2025 10:30",
        turismo: ["Turismoreligioso", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1013",
        origem: "LHR - Londres",
        destino: "Paris",
        companhia: "TAP",
        partida: "01/10/2025 08:00",
        chegada: "01/10/2025 09:20",
        direto: "S",
        custo: 75,
        imagem: "../img/misc/destinos/Paris/3.jpg",
        dataVolta: "06/10/2025 08:00",
        turismo: ["Turismocultural", "TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1014",
        origem: "FCO - Roma",
        destino: "Londres",
        companhia: "Ryanair",
        partida: "03/10/2025 12:00",
        chegada: "03/10/2025 14:20",
        direto: "N",
        custo: 95,
        imagem: "../img/misc/destinos/Londres/1.jpg",
        dataVolta: "08/10/2025 12:00",
        turismo: ["TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1015",
        origem: "CIA - Roma",
        destino: "Londres",
        companhia: "KLM",
        partida: "05/10/2025 07:45",
        chegada: "05/10/2025 09:50",
        direto: "S",
        custo: 160,
        imagem: "../img/misc/destinos/Londres/2.jpg",
        dataVolta: "10/10/2025 07:45",
        turismo: ["TurismoUrbano", "Turismocultural"],
      },
      {
        numeroVoo: "OP1016",
        origem: "AMS - Amesterdão",
        destino: "Londres",
        companhia: "TAP",
        partida: "07/10/2025 13:00",
        chegada: "07/10/2025 15:10",
        direto: "S",
        custo: 135,
        imagem: "../img/misc/destinos/Londres/3.jpg",
        dataVolta: "12/10/2025 13:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "OP1017",
        origem: "OPO - Porto",
        destino: "Londres",
        companhia: "Air France",
        partida: "09/10/2025 06:30",
        chegada: "09/10/2025 08:55",
        direto: "N",
        custo: 165,
        imagem: "../img/misc/destinos/Londres/1.jpg",
        dataVolta: "14/10/2025 06:30",
        turismo: ["Turismocultural", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1018",
        origem: "OPO - Porto",
        destino: "Paris",
        companhia: "Brussels Airlines",
        partida: "11/10/2025 11:15",
        chegada: "11/10/2025 13:20",
        direto: "S",
        custo: 150,
        imagem: "../img/misc/destinos/Paris/2.jpg",
        dataVolta: "16/10/2025 11:15",
        turismo: ["TurismoUrbano", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1019",
        origem: "OPO - Porto",
        destino: "Paris",
        companhia: "EasyJet",
        partida: "13/10/2025 07:00",
        chegada: "13/10/2025 09:30",
        direto: "S",
        custo: 140,
        imagem: "../img/misc/destinos/Paris/3.jpg",
        dataVolta: "18/10/2025 07:00",
        turismo: ["Turismocultural", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1020",
        origem: "OPO - Porto",
        destino: "Paris",
        companhia: "Ryanair",
        partida: "15/10/2025 12:00",
        chegada: "15/10/2025 14:45",
        direto: "N",
        custo: 100,
        imagem: "../img/misc/destinos/Paris/1.jpg",
        dataVolta: "20/10/2025 12:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "TP1234",
        origem: "OPO - Porto",
        destino: "Madrid",
        companhia: "TAP Air Portugal",
        partida: "17/10/2025 10:00",
        chegada: "17/10/2025 11:30",
        direto: "S",
        custo: 85,
        imagem: "../img/misc/destinos/Madrid/1.jpg",
        dataVolta: "22/10/2025 14:00",
        turismo: ["Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "FR5678",
        origem: "OPO - Porto",
        destino: "Paris",
        companhia: "Ryanair",
        partida: "19/10/2025 12:00",
        chegada: "19/10/2025 14:45",
        direto: "S",
        custo: 100,
        imagem: "../img/misc/destinos/Paris/2.jpg",
        dataVolta: "24/10/2025 12:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "EZY9101",
        origem: "OPO - Porto",
        destino: "Londres",
        companhia: "easyJet",
        partida: "21/10/2025 08:30",
        chegada: "21/10/2025 11:00",
        direto: "S",
        custo: 120,
        imagem: "../img/misc/destinos/Londres/1.jpg",
        dataVolta: "26/10/2025 16:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "BA2345",
        origem: "OPO - Porto",
        destino: "Dublin",
        companhia: "British Airways",
        partida: "23/10/2025 14:00",
        chegada: "23/10/2025 16:00",
        direto: "N",
        custo: 180,
        imagem: "../img/misc/destinos/Porto/1.jpg", // fallback para Porto pois Dublin não existe
        dataVolta: "28/10/2025 10:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "LH6789",
        origem: "OPO - Porto",
        destino: "Berlim",
        companhia: "Lufthansa",
        partida: "25/10/2025 09:00",
        chegada: "25/10/2025 12:30",
        direto: "S",
        custo: 150,
        imagem: "../img/misc/destinos/Porto/2.jpg", // fallback para Porto pois Berlim não existe
        dataVolta: "30/10/2025 15:00",
        turismo: ["Turismocultural", "TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "IB3456",
        origem: "OPO - Porto",
        destino: "Barcelona",
        companhia: "Iberia",
        partida: "27/10/2025 11:00",
        chegada: "27/10/2025 13:00",
        direto: "S",
        custo: 90,
        imagem: "../img/misc/destinos/Madrid/1.jpg", // fallback para Madrid pois Barcelona não existe
        dataVolta: "01/11/2025 18:00",
        turismo: [
          "TurismodeSolePraia",
          "Turismocultural",
          "Turismogastronomico",
        ],
      },
      {
        numeroVoo: "KL7890",
        origem: "OPO - Porto",
        destino: "Amsterdão",
        companhia: "KLM",
        partida: "02/11/2025 13:00",
        chegada: "02/11/2025 16:00",
        direto: "S",
        custo: 160,
        imagem: "../img/misc/destinos/Amsterdao/2.jpg",
        dataVolta: "07/11/2025 11:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "SK1234",
        origem: "OPO - Porto",
        destino: "Copenhaga",
        companhia: "SAS",
        partida: "04/11/2025 07:00",
        chegada: "04/11/2025 10:30",
        direto: "N",
        custo: 200,
        imagem: "../img/misc/destinos/Porto/1.jpg",
        dataVolta: "09/11/2025 09:00",
        turismo: ["Turismocultural", "Ecoturismo"],
      },
      {
        numeroVoo: "AF5678",
        origem: "OPO - Porto",
        destino: "Roma",
        companhia: "Air France",
        partida: "06/11/2025 10:00",
        chegada: "06/11/2025 13:00",
        direto: "S",
        custo: 140,
        imagem: "../img/misc/destinos/Roma/1.jpg",
        dataVolta: "11/11/2025 17:00",
        turismo: ["Turismoreligioso", "Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "VY9101",
        origem: "OPO - Porto",
        destino: "Milão",
        companhia: "Vueling",
        partida: "08/11/2025 15:00",
        chegada: "08/11/2025 17:30",
        direto: "S",
        custo: 95,
        imagem: "../img/misc/destinos/Porto/1.jpg",
        dataVolta: "13/11/2025 19:00",
        turismo: ["Turismodenegocios", "Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "TK2345",
        origem: "OPO - Porto",
        destino: "Istambul",
        companhia: "Turkish Airlines",
        partida: "10/11/2025 18:00",
        chegada: "10/11/2025 23:00",
        direto: "N",
        custo: 250,
        imagem: "../img/misc/destinos/Porto/1.jpg",
        dataVolta: "15/11/2025 14:00",
        turismo: ["Turismoreligioso", "Turismocultural", "Turismodenegocios"],
      },
      {
        numeroVoo: "LX6789",
        origem: "OPO - Porto",
        destino: "Zurique",
        companhia: "SWISS",
        partida: "12/11/2025 09:00",
        chegada: "12/11/2025 12:00",
        direto: "S",
        custo: 170,
        imagem: "../img/misc/destinos/Porto/1.jpg",
        dataVolta: "17/11/2025 10:00",
        turismo: ["Turismodenegocios", "Ecoturismo", "SaudeeBemEstar"],
      },
      {
        numeroVoo: "AUA1234",
        origem: "OPO - Porto",
        destino: "Viena",
        companhia: "Austrian Airlines",
        partida: "14/11/2025 11:00",
        chegada: "14/11/2025 14:30",
        direto: "S",
        custo: 155,
        imagem: "../img/misc/destinos/Porto/1.jpg",
        dataVolta: "19/11/2025 13:00",
        turismo: ["Turismocultural", "SaudeeBemEstar", "TurismoUrbano"],
      },
      {
        numeroVoo: "DY5678",
        origem: "OPO - Porto",
        destino: "Oslo",
        companhia: "Norwegian Air Shuttle",
        partida: "16/11/2025 16:00",
        chegada: "16/11/2025 19:00",
        direto: "N",
        custo: 210,
        imagem: "../img/misc/destinos/Porto/1.jpg",
        dataVolta: "21/11/2025 08:00",
        turismo: ["Ecoturismo", "Turismocultural"],
      },
      {
        numeroVoo: "EI9101",
        origem: "OPO - Porto",
        destino: "Dublin",
        companhia: "Aer Lingus",
        partida: "18/11/2025 08:00",
        chegada: "18/11/2025 10:00",
        direto: "S",
        custo: 130,
        imagem: "../img/misc/destinos/Porto/1.jpg",
        dataVolta: "23/11/2025 16:00",
        turismo: ["Turismocultural", "TurismoUrbano", "Turismogastronomico"],
      },
      {
        numeroVoo: "AZ2345",
        origem: "OPO - Porto",
        destino: "Florença",
        companhia: "ITA Airways",
        partida: "20/11/2025 13:00",
        chegada: "20/11/2025 16:00",
        direto: "N",
        custo: 190,
        imagem: "../img/misc/destinos/Porto/1.jpg",
        dataVolta: "25/11/2025 10:00",
        turismo: ["Turismocultural", "Turismorural", "Turismogastronomico"],
      },
      {
        numeroVoo: "SN6789",
        origem: "OPO - Porto",
        destino: "Bruxelas",
        companhia: "Brussels Airlines",
        partida: "22/11/2025 10:00",
        chegada: "22/11/2025 12:30",
        direto: "S",
        custo: 115,
        imagem: "../img/misc/destinos/Porto/1.jpg", // fallback image
        dataVolta: "27/11/2025 15:00",
        turismo: ["Turismodenegocios", "Turismogastronomico", "TurismoUrbano"],
      },
      {
        numeroVoo: "LO1234",
        origem: "OPO - Porto",
        destino: "Varsóvia",
        companhia: "LOT Polish Airlines",
        partida: "24/11/2025 14:00",
        chegada: "24/11/2025 17:30",
        direto: "N",
        custo: 220,
        imagem: "../img/misc/destinos/Porto/1.jpg", // fallback image
        dataVolta: "29/11/2025 09:00",
        turismo: ["Turismocultural", "Turismoreligioso", "TurismoUrbano"],
      },
      {
        numeroVoo: "RO5678",
        origem: "OPO - Porto",
        destino: "Bucareste",
        companhia: "TAROM",
        partida: "26/11/2025 09:30",
        chegada: "26/11/2025 13:00",
        direto: "N",
        custo: 230,
        imagem: "../img/misc/destinos/Porto/1.jpg", // fallback image
        dataVolta: "01/12/2025 11:00",
        turismo: ["Turismocultural", "Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "H69101",
        origem: "OPO - Porto",
        destino: "Budapeste",
        companhia: "Wizz Air",
        partida: "28/11/2025 17:00",
        chegada: "28/11/2025 20:00",
        direto: "S",
        custo: 80,
        imagem: "../img/misc/destinos/Porto/1.jpg", // fallback image
        dataVolta: "03/12/2025 14:00",
        turismo: ["Turismocultural", "SaudeeBemEstar", "TurismoUrbano"],
      },
      {
        numeroVoo: "AY2345",
        origem: "OPO - Porto",
        destino: "Helsínquia",
        companhia: "Finnair",
        partida: "01/12/2025 12:00",
        chegada: "01/12/2025 16:00",
        direto: "N",
        custo: 260,
        imagem: "../img/misc/destinos/Porto/1.jpg", // fallback image
        dataVolta: "06/12/2025 10:00",
        turismo: ["Ecoturismo", "Turismocultural", "TurismoUrbano"],
      },
    ];
    localStorage.setItem("viagens", JSON.stringify(viagens));
  }
}
