console.log("init.js carregado");

initdata();

function initdata() {
  // Utilizador inicial
  if (!localStorage.user) {
    const user = [
      {
        username: "António Amorim",
        avatar: "/img/users/40240119.jpg",
        pontos: "3500",
        email: "40240119@esmad.ipp.pt",
        password: "40240119",
        private: false,
        admin: false,
      },
      {
        username: "Gabriel Paiva",
        avatar: "/img/users/40240137.jpg",
        pontos: "0",
        email: "40240137@esmad.ipp.pt",
        password: "40240137",
        private: false,
        admin: true,
      },
    ];
    localStorage.setItem("user", JSON.stringify(user));
  }
  // Aeroportos
  if (!localStorage.aeroportos) {
    const aeroportos = [
      {
        codigo: "OPO",
        cidade: "Porto",
        pais: "Portugal",
        location: { latitude: 41.2421, longitude: -8.6781 },
      },
      {
        codigo: "LIS",
        cidade: "Lisboa",
        pais: "Portugal",
        location: { latitude: 38.7742, longitude: -9.1342 },
      },
      {
        codigo: "LHR",
        cidade: "Londres",
        pais: "Reino Unido",
        location: { latitude: 51.47, longitude: -0.4543 },
      },
      {
        codigo: "LGW",
        cidade: "Londres",
        pais: "Reino Unido",
        location: { latitude: 51.1537, longitude: -0.1821 },
      },
      {
        codigo: "STN",
        cidade: "Londres",
        pais: "Reino Unido",
        location: { latitude: 51.885, longitude: 0.235 },
      },
      {
        codigo: "LTN",
        cidade: "Londres",
        pais: "Reino Unido",
        location: { latitude: 51.8747, longitude: -0.3683 },
      },
      {
        codigo: "LCY",
        cidade: "Londres",
        pais: "Reino Unido",
        location: { latitude: 51.5053, longitude: 0.0553 },
      },
      {
        codigo: "CDG",
        cidade: "Paris",
        pais: "França",
        location: { latitude: 49.0097, longitude: 2.5479 },
      },
      {
        codigo: "ORY",
        cidade: "Paris",
        pais: "França",
        location: { latitude: 48.7262, longitude: 2.3652 },
      },
      {
        codigo: "BVA",
        cidade: "Paris",
        pais: "França",
        location: { latitude: 49.4544, longitude: 2.1128 },
      },
      {
        codigo: "AMS",
        cidade: "Amesterdão",
        pais: "Países Baixos",
        location: { latitude: 52.3105, longitude: 4.7683 },
      },
      {
        codigo: "MAD",
        cidade: "Madrid",
        pais: "Espanha",
        location: { latitude: 40.4983, longitude: -3.5676 },
      },
      {
        codigo: "FCO",
        cidade: "Roma",
        pais: "Itália",
        location: { latitude: 41.8003, longitude: 12.2389 },
      },
      {
        codigo: "CIA",
        cidade: "Roma",
        pais: "Itália",
        location: { latitude: 41.7999, longitude: 12.5949 },
      },
    ];
    localStorage.setItem("aeroportos", JSON.stringify(aeroportos));
  }
  // Destinos
  if (!localStorage.destinos) {
    const destinos = [
      {
        id: 1,
        cidade: "Porto",
        pais: "Portugal",
        aeroporto: "OPO",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Gastronómico",
          "Enoturismo",
        ],
        acessibilidade: [
          "Acesso Sem Degraus (variável)",
          "Transporte Acessível (Metro)",
        ],
      },
      {
        id: 2,
        cidade: "Lisboa",
        pais: "Portugal",
        aeroporto: "LIS",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Urbano",
          "Turismo Histórico",
          "Turismo Gastronómico",
        ],
        acessibilidade: [
          "Transporte Acessível (Metro)",
          "Elevadores Disponíveis",
          "Acesso Sem Degraus (variável)",
        ],
      },
      {
        id: 3,
        cidade: "Londres",
        pais: "Reino Unido",
        aeroporto: "LHR",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Urbano",
          "Turismo de Negócios",
          "Compras",
        ],
        acessibilidade: [
          "Transporte Acessível",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
          "Aluguer de Equipamento de Mobilidade",
        ],
      },
      {
        id: 4,
        cidade: "Londres",
        pais: "Reino Unido",
        aeroporto: "LGW",
        tiposTurismo: ["Turismo Cultural", "Turismo Urbano"],
        acessibilidade: ["Transporte Acessível", "Elevadores Disponíveis"],
      },
      {
        id: 5,
        cidade: "Londres",
        pais: "Reino Unido",
        aeroporto: "STN",
        tiposTurismo: ["Turismo Cultural", "Turismo Urbano"],
        acessibilidade: [
          "Transporte Acessível (comboio)",
          "Elevadores Disponíveis",
        ],
      },
      {
        id: 6,
        cidade: "Londres",
        pais: "Reino Unido",
        aeroporto: "LTN",
        tiposTurismo: ["Turismo Cultural", "Turismo Urbano"],
        acessibilidade: [
          "Transporte Acessível (comboio/bus)",
          "Elevadores Disponíveis",
        ],
      },
      {
        id: 7,
        cidade: "Londres",
        pais: "Reino Unido",
        aeroporto: "LCY",
        tiposTurismo: ["Turismo de Negócios", "Turismo Urbano"],
        acessibilidade: [
          "Transporte Acessível (DLR)",
          "Elevadores Disponíveis",
          "Acesso Sem Degraus",
        ],
      },
      {
        id: 8,
        cidade: "Paris",
        pais: "França",
        aeroporto: "CDG",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Gastronómico",
          "Turismo Urbano",
          "Moda",
        ],
        acessibilidade: [
          "Transporte Acessível (RER/Metro)",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 9,
        cidade: "Paris",
        pais: "França",
        aeroporto: "ORY",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Gastronómico",
          "Turismo Urbano",
        ],
        acessibilidade: [
          "Transporte Acessível (Orlyval/Bus)",
          "Elevadores Disponíveis",
        ],
      },
      {
        id: 10,
        cidade: "Paris",
        pais: "França",
        aeroporto: "BVA",
        tiposTurismo: ["Turismo Cultural", "Turismo Urbano"],
        acessibilidade: ["Transporte Acessível (Bus para Paris)"],
      },
      {
        id: 11,
        cidade: "Amesterdão",
        pais: "Países Baixos",
        aeroporto: "AMS",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Urbano",
          "Museus",
          "Ciclismo",
        ],
        acessibilidade: [
          "Transporte Acessível (excelente)",
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 12,
        cidade: "Madrid",
        pais: "Espanha",
        aeroporto: "MAD",
        tiposTurismo: [
          "Turismo Cultural",
          "Turismo Gastronómico",
          "Vida Noturna",
          "Turismo Urbano",
        ],
        acessibilidade: [
          "Transporte Acessível (Metro excelente)",
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 13,
        cidade: "Roma",
        pais: "Itália",
        aeroporto: "FCO",
        tiposTurismo: [
          "Turismo Histórico",
          "Turismo Cultural",
          "Turismo Religioso",
          "Turismo Gastronómico",
        ],
        acessibilidade: [
          "Transporte Acessível (comboio/bus)",
          "Acesso Sem Degraus (desafiador)",
          "Elevadores Disponíveis (limitado)",
        ],
      },
      {
        id: 14,
        cidade: "Roma",
        pais: "Itália",
        aeroporto: "CIA",
        tiposTurismo: [
          "Turismo Histórico",
          "Turismo Cultural",
          "Turismo Religioso",
        ],
        acessibilidade: [
          "Transporte Acessível (Bus)",
          "Acesso Sem Degraus (desafiador)",
        ],
      },
    ];
    localStorage.setItem("destinos", JSON.stringify(destinos));
  }
  // Hoteis
    const hoteis = [
      {
        id: 1,
        cidade: "Porto",
        nome: "Hotel Infante Sagres",
        foto: "https://placehold.co/600x400/E1C4A9/5C4033?text=Hotel+Porto+1",
        quartos: [
          {
            tipo: "Deluxe",
            camas: 1,
            capacidade: 2,
            precoNoite: 250,
            foto: "https://placehold.co/300x200/F0E6DD/A0522D?text=Quarto+Deluxe",
            acessibilidade: ["Elevadores Disponíveis"],
            dataCheckin: "2025-07-03",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Ginásio", "Bar"],
            wifiGratis: true,
            descricao:
              "Quarto espaçoso com decoração clássica e vista para a cidade.",
          },
        ],
      },
      {
        id: 2,
        cidade: "Porto",
        nome: "The Yeatman Hotel",
        foto: "https://placehold.co/600x400/D4AF37/8B4513?text=Hotel+Porto+2",
        quartos: [
          {
            tipo: "Suite Superior Vista Rio",
            camas: 1,
            capacidade: 2,
            precoNoite: 450,
            foto: "https://placehold.co/300x200/FFDAB9/800000?text=Suite+Rio",
            acessibilidade: ["Acesso Sem Degraus", "Casas de Banho Adaptadas"],
            dataCheckin: "2025-07-15",
            numeroNoites: 4,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Restaurante Gourmet", "Bar"],
            wifiGratis: true,
            descricao:
              "Suite luxuosa com varanda e vista panorâmica para o Douro.",
          },
        ],
      },
      {
        id: 3,
        cidade: "Porto",
        nome: "Pestana Vintage Porto Hotel",
        foto: "https://placehold.co/600x400/A0522D/F5F5DC?text=Hotel+Porto+3",
        quartos: [
          {
            tipo: "Vintage Classic",
            camas: 1,
            capacidade: 2,
            precoNoite: 280,
            foto: "https://placehold.co/300x200/DEB887/8B4513?text=Quarto+Vintage",
            acessibilidade: ["Elevadores Disponíveis"],
            dataCheckin: "2025-07-21",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Bar", "Restaurante", "Serviço de Quartos"],
            wifiGratis: true,
            descricao: "Quarto clássico com vista para o rio Douro.",
          },
        ],
      },
      {
        id: 4,
        cidade: "Porto",
        nome: "Hotel Carris Porto Ribeira",
        foto: "https://placehold.co/600x400/B8860B/FFFFFF?text=Hotel+Porto+4",
        quartos: [
          {
            tipo: "Standard",
            camas: 1,
            capacidade: 2,
            precoNoite: 150,
            foto: "https://placehold.co/300x200/F4A460/000000?text=Quarto+Standard",
            acessibilidade: ["Quartos Adaptados"],
            dataCheckin: "2025-07-10",
            numeroNoites: 5,
            pequenoAlmocoIncluido: true,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto confortável no centro histórico do Porto.",
          },
        ],
      },
      {
        id: 5,
        cidade: "Porto",
        nome: "Torel Avantgarde",
        foto: "https://placehold.co/600x400/8B4513/FFFFE0?text=Hotel+Porto+5",
        quartos: [
          {
            tipo: "Executivo Vista Rio",
            camas: 1,
            capacidade: 2,
            precoNoite: 320,
            foto: "https://placehold.co/300x200/CD853F/F5F5F5?text=Quarto+Executivo",
            acessibilidade: ["Elevadores Disponíveis", "Acesso Sem Degraus"],
            dataCheckin: "2025-07-28",
            numeroNoites: 3,
            pequenoAlmocoIncluido: false,
            comodidades: ["Piscina", "Bar", "Estacionamento"],
            wifiGratis: true,
            descricao:
              "Quarto executivo com decoração moderna e vista para o rio.",
          },
        ],
      },
      {
        id: 6,
        cidade: "Lisboa",
        nome: "Four Seasons Hotel Ritz Lisbon",
        foto: "https://placehold.co/600x400/ADD8E6/000080?text=Hotel+Lisboa+1",
        quartos: [
          {
            tipo: "Quarto Premier",
            camas: 1,
            capacidade: 2,
            precoNoite: 600,
            foto: "https://placehold.co/300x200/B0E0E6/4682B4?text=Quarto+Premier",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Quartos Adaptados",
              "Casas de Banho Adaptadas",
            ],
            dataCheckin: "2025-07-05",
            numeroNoites: 4,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Ginásio", "Restaurante"],
            wifiGratis: true,
            descricao:
              "Quarto premier com varanda e vista para o parque Eduardo VII.",
          },
        ],
      },
      {
        id: 7,
        cidade: "Lisboa",
        nome: "Bairro Alto Hotel",
        foto: "https://placehold.co/600x400/87CEEB/0000CD?text=Hotel+Lisboa+2",
        quartos: [
          {
            tipo: "Suite Chiado",
            camas: 1,
            capacidade: 2,
            precoNoite: 480,
            foto: "https://placehold.co/300x200/AFEEEE/191970?text=Suite+Chiado",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Aceita Cães-Guia/Assistência",
            ],
            dataCheckin: "2025-07-12",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Bar", "Restaurante", "Terraço"],
            wifiGratis: true,
            descricao: "Suite elegante no coração do bairro Alto.",
          },
        ],
      },
      {
        id: 8,
        cidade: "Lisboa",
        nome: "Memmo Alfama - Design Hotels",
        foto: "https://placehold.co/600x400/B0C4DE/708090?text=Hotel+Lisboa+3",
        quartos: [
          {
            tipo: "Quarto Terraço Vista Rio",
            camas: 1,
            capacidade: 2,
            precoNoite: 350,
            foto: "https://placehold.co/300x200/E6E6FA/778899?text=Quarto+Vista",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Acesso Sem Degraus (limitado)",
            ],
            dataCheckin: "2025-07-18",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Piscina", "Bar", "Restaurante"],
            wifiGratis: true,
            descricao: "Quarto com terraço privado e vista para o rio Tejo.",
          },
        ],
      },
      {
        id: 9,
        cidade: "Lisboa",
        nome: "Corinthia Lisbon",
        foto: "https://placehold.co/600x400/4682B4/F0F8FF?text=Hotel+Lisboa+4",
        quartos: [
          {
            tipo: "Deluxe King",
            camas: 1,
            capacidade: 2,
            precoNoite: 280,
            foto: "https://placehold.co/300x200/87CEFA/2F4F4F?text=Quarto+Deluxe",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Quartos Adaptados",
              "Spa Acessível",
            ],
            dataCheckin: "2025-07-23",
            numeroNoites: 5,
            pequenoAlmocoIncluido: true,
            comodidades: ["Spa", "Piscina", "Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto deluxe com acesso ao spa e piscina interior.",
          },
        ],
      },
      {
        id: 10,
        cidade: "Lisboa",
        nome: "The Lumiares Hotel & Spa",
        foto: "https://placehold.co/600x400/6495ED/F8F8FF?text=Hotel+Lisboa+5",
        quartos: [
          {
            tipo: "Apartamento Penthouse",
            camas: 2,
            capacidade: 4,
            precoNoite: 550,
            foto: "https://placehold.co/300x200/B0E0E6/4169E1?text=Penthouse",
            acessibilidade: ["Elevadores Disponíveis", "Acesso Sem Degraus"],
            dataCheckin: "2025-07-30",
            numeroNoites: 6,
            pequenoAlmocoIncluido: true,
            comodidades: ["Spa", "Restaurante", "Bar", "Estacionamento"],
            wifiGratis: true,
            descricao:
              "Penthouse espaçosa com cozinha equipada e vista panorâmica.",
          },
        ],
      },
      {
        id: 11,
        cidade: "Londres",
        nome: "The Savoy",
        foto: "https://placehold.co/600x400/36454F/E0E0E0?text=Hotel+Londres+1",
        quartos: [
          {
            tipo: "Edwardian Suite",
            camas: 1,
            capacidade: 2,
            precoNoite: 1200,
            foto: "https://placehold.co/300x200/708090/F5F5F5?text=Suite+Edwardian",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Quartos Adaptados",
              "Aceita Cães-Guia/Assistência",
            ],
          },
        ],
      },
      {
        id: 12,
        cidade: "Londres",
        nome: "The Ritz London",
        foto: "https://placehold.co/600x400/465945/FFFACD?text=Hotel+Londres+2",
        quartos: [
          {
            tipo: "Superior King",
            camas: 1,
            capacidade: 2,
            precoNoite: 800,
            foto: "https://placehold.co/300x200/8FBC8F/FAF0E6?text=Quarto+Superior",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Acesso Sem Degraus (com assistência)",
            ],
          },
        ],
      },
      {
        id: 13,
        cidade: "Londres",
        nome: "Shangri-La The Shard, London",
        foto: "https://placehold.co/600x400/536878/F0FFFF?text=Hotel+Londres+3",
        quartos: [
          {
            tipo: "Quarto Premier Shard",
            camas: 1,
            capacidade: 2,
            precoNoite: 750,
            foto: "https://placehold.co/300x200/A0AEC0/E6F0FF?text=Quarto+Shard",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Acesso Sem Degraus",
              "Quartos Adaptados",
            ],
          },
        ],
      },
      {
        id: 14,
        cidade: "Londres",
        nome: "The Langham, London",
        foto: "https://placehold.co/600x400/6A5ACD/FFE4E1?text=Hotel+Londres+4",
        quartos: [
          {
            tipo: "Executivo",
            camas: 1,
            capacidade: 2,
            precoNoite: 650,
            foto: "https://placehold.co/300x200/B0A4E3/FFF0F5?text=Quarto+Executivo",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Acesso Sem Degraus",
              "Casas de Banho Adaptadas",
            ],
          },
        ],
      },
      {
        id: 15,
        cidade: "Londres",
        nome: "The Z Hotel Piccadilly",
        foto: "https://placehold.co/600x400/778899/F8F8FF?text=Hotel+Londres+5",
        quartos: [
          {
            tipo: "Z Double",
            camas: 1,
            capacidade: 2,
            precoNoite: 180,
            foto: "https://placehold.co/300x200/BCC6CC/F5F5F5?text=Quarto+Z",
            acessibilidade: ["Elevadores Disponíveis"],
          },
        ],
      },
      {
        id: 16,
        cidade: "Paris",
        nome: "Hôtel Plaza Athénée",
        foto: "https://placehold.co/600x400/FF6347/FFF5EE?text=Hotel+Paris+1",
        quartos: [
          {
            tipo: "Suite Eiffel Signature",
            camas: 1,
            capacidade: 2,
            precoNoite: 2500,
            foto: "https://placehold.co/300x200/FFA07A/FFEBCD?text=Suite+Eiffel",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Quartos Adaptados",
            ],
          },
        ],
      },
      {
        id: 17,
        cidade: "Paris",
        nome: "Le Bristol Paris",
        foto: "https://placehold.co/600x400/FF7F50/FDF5E6?text=Hotel+Paris+2",
        quartos: [
          {
            tipo: "Quarto Deluxe com Jardim",
            camas: 1,
            capacidade: 2,
            precoNoite: 1500,
            foto: "https://placehold.co/300x200/FFB347/FFF8DC?text=Quarto+Jardim",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Aceita Cães-Guia/Assistência",
            ],
          },
        ],
      },
      {
        id: 18,
        cidade: "Paris",
        nome: "Mandarin Oriental, Paris",
        foto: "https://placehold.co/600x400/FF8C00/FFFFF0?text=Hotel+Paris+3",
        quartos: [
          {
            tipo: "Suite Couture",
            camas: 1,
            capacidade: 2,
            precoNoite: 1800,
            foto: "https://placehold.co/300x200/FFA500/F5FFFA?text=Suite+Couture",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Spa Acessível",
            ],
          },
        ],
      },
      {
        id: 19,
        cidade: "Paris",
        nome: "Hotel Lutetia",
        foto: "https://placehold.co/600x400/FF4500/FFFAFA?text=Hotel+Paris+4",
        quartos: [
          {
            tipo: "Junior Suite Art Deco",
            camas: 1,
            capacidade: 2,
            precoNoite: 1100,
            foto: "https://placehold.co/300x200/FF6347/F8F8FF?text=Suite+Art+Deco",
            acessibilidade: ["Elevadores Disponíveis", "Quartos Adaptados"],
          },
        ],
      },
      {
        id: 20,
        cidade: "Paris",
        nome: "Generator Paris",
        foto: "https://placehold.co/600x400/FF0000/FFFFFF?text=Hostel+Paris+5",
        quartos: [
          {
            tipo: "Cama em Dormitório Premium",
            camas: 1,
            capacidade: 1,
            precoNoite: 40,
            foto: "https://placehold.co/300x200/FA8072/F5F5F5?text=Dorm+Premium",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Ambiente Acolhedor LGBTQIA+",
            ],
          },
        ],
      },
      {
        id: 21,
        cidade: "Amesterdão",
        nome: "Conservatorium Hotel",
        foto: "https://placehold.co/600x400/008080/E0FFFF?text=Hotel+Amesterdão+1",
        quartos: [
          {
            tipo: "Suite Duplex",
            camas: 1,
            capacidade: 2,
            precoNoite: 700,
            foto: "https://placehold.co/300x200/20B2AA/F0FFFF?text=Suite+Duplex",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Piscina Acessível",
            ],
          },
        ],
      },
      {
        id: 22,
        cidade: "Amesterdão",
        nome: "Pulitzer Amsterdam",
        foto: "https://placehold.co/600x400/48D1CC/F5FFFA?text=Hotel+Amesterdão+2",
        quartos: [
          {
            tipo: "Quarto Generoso Vista Canal",
            camas: 1,
            capacidade: 2,
            precoNoite: 550,
            foto: "https://placehold.co/300x200/AFEEEE/F0FFF0?text=Quarto+Canal",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Aceita Cães-Guia/Assistência",
            ],
          },
        ],
      },
      {
        id: 23,
        cidade: "Amesterdão",
        nome: "The Hoxton, Amsterdam",
        foto: "https://placehold.co/600x400/40E0D0/F8F8FF?text=Hotel+Amesterdão+3",
        quartos: [
          {
            tipo: "Cosy Room",
            camas: 1,
            capacidade: 2,
            precoNoite: 280,
            foto: "https://placehold.co/300x200/7FFFD4/F5F5F5?text=Quarto+Cosy",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Ambiente Acolhedor LGBTQIA+",
            ],
          },
        ],
      },
      {
        id: 24,
        cidade: "Amesterdão",
        nome: "Hotel V Nesplein",
        foto: "https://placehold.co/600x400/00CED1/FFFACD?text=Hotel+Amesterdão+4",
        quartos: [
          {
            tipo: "Loft",
            camas: 1,
            capacidade: 2,
            precoNoite: 350,
            foto: "https://placehold.co/300x200/5F9EA0/FFF8DC?text=Quarto+Loft",
            acessibilidade: ["Elevadores Disponíveis"],
          },
        ],
      },
      {
        id: 25,
        cidade: "Amesterdão",
        nome: "Flying Pig Downtown Hostel",
        foto: "https://placehold.co/600x400/5F9EA0/FFFAF0?text=Hostel+Amesterdão+5",
        quartos: [
          {
            tipo: "Cama em Dormitório Misto",
            camas: 1,
            capacidade: 1,
            precoNoite: 35,
            foto: "https://placehold.co/300x200/B0E0E6/F5F5DC?text=Dorm+Misto",
            acessibilidade: [],
          },
        ],
      },
      {
        id: 26,
        cidade: "Madrid",
        nome: "Four Seasons Hotel Madrid",
        foto: "https://placehold.co/600x400/FFD700/8B0000?text=Hotel+Madrid+1",
        quartos: [
          {
            tipo: "Suite Real",
            camas: 1,
            capacidade: 2,
            precoNoite: 3000,
            foto: "https://placehold.co/300x200/F0E68C/B22222?text=Suite+Real",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Quartos Adaptados",
            ],
            dataCheckin: "2025-07-05",
            numeroNoites: 4,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Ginásio", "Restaurante"],
            wifiGratis: true,
            descricao:
              "Suite real com decoração luxuosa e vista para o palácio real.",
          },
        ],
      },
      {
        id: 27,
        cidade: "Madrid",
        nome: "Hotel Regina",
        foto: "https://placehold.co/600x400/FFA500/A52A2A?text=Hotel+Madrid+2",
        quartos: [
          {
            tipo: "Duplo Superior",
            camas: 1,
            capacidade: 2,
            precoNoite: 180,
            foto: "https://placehold.co/300x200/FFEC8B/800000?text=Quarto+Superior",
            acessibilidade: ["Elevadores Disponíveis"],
            dataCheckin: "2025-07-10",
            numeroNoites: 5,
            pequenoAlmocoIncluido: true,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto duplo superior com decoração moderna.",
          },
        ],
      },
      {
        id: 28,
        cidade: "Madrid",
        nome: "Only YOU Boutique Hotel Madrid",
        foto: "https://placehold.co/600x400/FF8C00/FFFFFF?text=Hotel+Madrid+3",
        quartos: [
          {
            tipo: "Deluxe Premium",
            camas: 1,
            capacidade: 2,
            precoNoite: 350,
            foto: "https://placehold.co/300x200/FFDAB9/000000?text=Quarto+Premium",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Ambiente Acolhedor LGBTQIA+",
            ],
            dataCheckin: "2025-07-15",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto deluxe com decoração elegante e moderna.",
          },
        ],
      },
      {
        id: 29,
        cidade: "Madrid",
        nome: "Pestana Plaza Mayor Madrid",
        foto: "https://placehold.co/600x400/CD853F/F5F5DC?text=Hotel+Madrid+4",
        quartos: [
          {
            tipo: "Quarto Histórico",
            camas: 1,
            capacidade: 2,
            precoNoite: 280,
            foto: "https://placehold.co/300x200/F4A460/8B4513?text=Quarto+Histórico",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Piscina Acessível",
            ],
            dataCheckin: "2025-07-20",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto histórico com decoração clássica.",
          },
        ],
      },
      {
        id: 30,
        cidade: "Madrid",
        nome: "The Hat Madrid",
        foto: "https://placehold.co/600x400/D2691E/FFFFF0?text=Hostel+Madrid+5",
        quartos: [
          {
            tipo: "Cama em Dormitório 4 camas",
            camas: 1,
            capacidade: 1,
            precoNoite: 30,
            foto: "https://placehold.co/300x200/FF7F50/F8F8FF?text=Dorm+4+camas",
            acessibilidade: ["Elevadores Disponíveis"],
          },
        ],
      },
      {
        id: 31,
        cidade: "Roma",
        nome: "Hotel Eden - Dorchester Collection",
        foto: "https://placehold.co/600x400/B22222/FFF5EE?text=Hotel+Roma+1",
        quartos: [
          {
            tipo: "Suite Villa Medici Penthouse",
            camas: 1,
            capacidade: 2,
            precoNoite: 4000,
            foto: "https://placehold.co/300x200/CD5C5C/FFFAFA?text=Suite+Penthouse",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Quartos Adaptados",
            ],
            dataCheckin: "2025-07-05",
            numeroNoites: 4,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Restaurante", "Bar"],
            wifiGratis: true,
            descricao:
              "Suite penthouse com decoração luxuosa e vista para a cidade eterna.",
          },
        ],
      },
      {
        id: 32,
        cidade: "Roma",
        nome: "Hotel Artemide",
        foto: "https://placehold.co/600x400/A52A2A/F5F5F5?text=Hotel+Roma+2",
        quartos: [
          {
            tipo: "Duplo Comfort",
            camas: 1,
            capacidade: 2,
            precoNoite: 250,
            foto: "https://placehold.co/300x200/E9967A/F8F8FF?text=Quarto+Comfort",
            acessibilidade: ["Elevadores Disponíveis", "Spa Acessível"],
            dataCheckin: "2025-07-10",
            numeroNoites: 5,
            pequenoAlmocoIncluido: true,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto duplo confortável com decoração moderna.",
          },
        ],
      },
      {
        id: 33,
        cidade: "Roma",
        nome: "St. Regis Rome",
        foto: "https://placehold.co/600x400/8B0000/FFF0F5?text=Hotel+Roma+3",
        quartos: [
          {
            tipo: "Imperial Room",
            camas: 1,
            capacidade: 2,
            precoNoite: 700,
            foto: "https://placehold.co/300x200/DC143C/FFFAF0?text=Quarto+Imperial",
            acessibilidade: [
              "Acesso Sem Degraus",
              "Elevadores Disponíveis",
              "Aceita Cães-Guia/Assistência",
            ],
            dataCheckin: "2025-07-15",
            numeroNoites: 3,
            pequenoAlmocoIncluido: true,
            comodidades: ["Piscina", "Spa", "Restaurante", "Bar"],
            wifiGratis: true,
            descricao:
              "Quarto imperial com decoração luxuosa e vista para a cidade.",
          },
        ],
      },
      {
        id: 34,
        cidade: "Roma",
        nome: "Hotel Vilòn - Small Luxury Hotels of the World",
        foto: "https://placehold.co/600x400/800000/FFF8DC?text=Hotel+Roma+4",
        quartos: [
          {
            tipo: "Vilòn Charming",
            camas: 1,
            capacidade: 2,
            precoNoite: 550,
            foto: "https://placehold.co/300x200/BC8F8F/FFFFF0?text=Quarto+Charming",
            acessibilidade: ["Elevadores Disponíveis", "Pátio Acessível"],
            dataCheckin: "2025-07-20",
            numeroNoites: 2,
            pequenoAlmocoIncluido: false,
            comodidades: ["Restaurante", "Bar"],
            wifiGratis: true,
            descricao: "Quarto encantador com acesso a pátio privado.",
          },
        ],
      },
      {
        id: 35,
        cidade: "Roma",
        nome: "The RomeHello Hostel",
        foto: "https://placehold.co/600x400/A0522D/FFFFFF?text=Hostel+Roma+5",
        quartos: [
          {
            tipo: "Cama em Dormitório Feminino",
            camas: 1,
            capacidade: 1,
            precoNoite: 38,
            foto: "https://placehold.co/300x200/D2B48C/F5F5F5?text=Dorm+Feminino",
            acessibilidade: [
              "Elevadores Disponíveis",
              "Acesso Sem Degraus (limitado)",
            ],
          },
        ],
      },
    ];
    localStorage.setItem("hoteis", JSON.stringify(hoteis));
  }
  // Atividades
  if (!localStorage.atividades) {
    const atividades = [
      {
        id: 1,
        destinoId: 1,
        tipoTurismo: "Enoturismo",
        nome: "Cruzeiro das 6 Pontes e Visita a Cave",
        foto: "https://placehold.co/600x400/A0522D/FFFFFF?text=Atividade+Porto+1",
        descricao:
          "Combine um cruzeiro panorâmico com uma prova de Vinho do Porto.",
        acessibilidade: [
          "Acesso Sem Degraus (barco variável)",
          "Elevadores Disponíveis (algumas caves)",
        ],
      },
      {
        id: 2,
        destinoId: 1,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita Guiada à Torre dos Clérigos",
        foto: "https://placehold.co/600x400/B8860B/000000?text=Atividade+Porto+2",
        descricao:
          "Suba à torre para vistas incríveis e conheça a igreja barroca.",
        acessibilidade: ["Elevadores Disponíveis (parcial)", "Muitos degraus"],
      },
      {
        id: 3,
        destinoId: 1,
        tipoTurismo: "Turismo Cultural",
        nome: "Entrada na Livraria Lello",
        foto: "https://placehold.co/600x400/8B4513/FFFFFF?text=Atividade+Porto+3",
        descricao: "Visite uma das livrarias mais famosas do mundo.",
        acessibilidade: ["Acesso Sem Degraus (limitado)", "Multidões"],
      },
      {
        id: 4,
        destinoId: 1,
        tipoTurismo: "Turismo Urbano",
        nome: "Passeio de Tuk Tuk pela Ribeira e Centro Histórico",
        foto: "https://placehold.co/600x400/CD853F/000000?text=Atividade+Porto+4",
        descricao:
          "Descubra os cantos pitorescos da cidade de forma divertida.",
        acessibilidade: ["Transporte Acessível (variável)"],
      },
      {
        id: 5,
        destinoId: 1,
        tipoTurismo: "Turismo Gastronómico",
        nome: "Workshop de Pastel de Nata no Porto",
        foto: "https://placehold.co/600x400/F4A460/FFFFFF?text=Atividade+Porto+5",
        descricao: "Aprenda a fazer o famoso doce português.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Opções Alimentares Específicas (informar)",
        ],
      },
      {
        id: 6,
        destinoId: 2,
        tipoTurismo: "Turismo Histórico",
        nome: "Visita Guiada ao Mosteiro dos Jerónimos",
        foto: "https://placehold.co/600x400/ADD8E6/000000?text=Atividade+Lisboa+1",
        descricao: "Explore a obra-prima do estilo manuelino.",
        acessibilidade: [
          "Acesso Sem Degraus (parcial)",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 7,
        destinoId: 2,
        tipoTurismo: "Turismo Urbano",
        nome: "Tour a Pé por Alfama e Castelo",
        foto: "https://placehold.co/600x400/87CEEB/000000?text=Atividade+Lisboa+2",
        descricao:
          "Perca-se nas ruas estreitas e descubra vistas deslumbrantes.",
        acessibilidade: [
          "Acesso Sem Degraus (muito limitado)",
          "Percurso com subidas",
        ],
      },
      {
        id: 8,
        destinoId: 2,
        tipoTurismo: "Turismo Cultural",
        nome: "Espetáculo de Fado com Jantar",
        foto: "https://placehold.co/600x400/B0C4DE/000000?text=Atividade+Lisboa+3",
        descricao: "Viva a emoção da música tradicional portuguesa.",
        acessibilidade: [
          "Acesso Sem Degraus (depende do local)",
          "Ambientes Sensoriais Calmos (relativamente)",
        ],
      },
      {
        id: 9,
        destinoId: 2,
        tipoTurismo: "Turismo Gastronómico",
        nome: "Tour de Elétrico 28 com Prova de Pastéis de Belém",
        foto: "https://placehold.co/600x400/4682B4/FFFFFF?text=Atividade+Lisboa+4",
        descricao: "Combine o icónico elétrico com o doce mais famoso.",
        acessibilidade: ["Transporte Acessível (muito limitado no elétrico)"],
      },
      {
        id: 10,
        destinoId: 2,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita ao Museu Nacional do Azulejo",
        foto: "https://placehold.co/600x400/6495ED/000000?text=Atividade+Lisboa+5",
        descricao: "Descubra a história e a arte do azulejo português.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 11,
        destinoId: 3,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita à Torre de Londres e Joias da Coroa",
        foto: "https://placehold.co/600x400/36454F/FFFFFF?text=Atividade+Londres+1",
        descricao: "Explore a história e veja as famosas joias.",
        acessibilidade: [
          "Acesso Sem Degraus (limitado)",
          "Aluguer de Equipamento de Mobilidade",
          "Guia Áudio",
        ],
      },
      {
        id: 12,
        destinoId: 4,
        tipoTurismo: "Turismo Urbano",
        nome: "Passeio no London Eye com Vista Panorâmica",
        foto: "https://placehold.co/600x400/465945/000000?text=Atividade+Londres+2",
        descricao: "Desfrute de vistas de 360 graus sobre a cidade.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas (próximo)",
        ],
      },
      {
        id: 13,
        destinoId: 5,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita ao British Museum",
        foto: "https://placehold.co/600x400/536878/FFFFFF?text=Atividade+Londres+3",
        descricao: "Descubra tesouros de todo o mundo.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
          "Informação em Braille/Áudio (limitado)",
        ],
      },
      {
        id: 14,
        destinoId: 6,
        tipoTurismo: "Turismo Urbano",
        nome: "Tour pelos Mercados de Londres (Borough, Camden)",
        foto: "https://placehold.co/600x400/6A5ACD/000000?text=Atividade+Londres+4",
        descricao: "Experimente a diversidade gastronómica e cultural.",
        acessibilidade: ["Acesso Sem Degraus (variável)", "Multidões"],
      },
      {
        id: 15,
        destinoId: 7,
        tipoTurismo: "Turismo Cultural",
        nome: "Bilhete para Musical no West End",
        foto: "https://placehold.co/600x400/778899/FFFFFF?text=Atividade+Londres+5",
        descricao: "Assista a um espetáculo de renome mundial.",
        acessibilidade: [
          "Acesso Sem Degraus (verificar teatro)",
          "Casas de Banho Adaptadas (verificar teatro)",
        ],
      },
      {
        id: 16,
        destinoId: 8,
        tipoTurismo: "Turismo Cultural",
        nome: "Bilhete Sem Fila para o Museu do Louvre",
        foto: "https://placehold.co/600x400/FF6347/000000?text=Atividade+Paris+1",
        descricao: "Evite as filas e veja obras-primas como a Mona Lisa.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
          "Aluguer de Equipamento de Mobilidade",
        ],
      },
      {
        id: 17,
        destinoId: 9,
        tipoTurismo: "Turismo Urbano",
        nome: "Subida ao 2º Andar ou Topo da Torre Eiffel",
        foto: "https://placehold.co/600x400/FF7F50/000000?text=Atividade+Paris+2",
        descricao: "A vista icónica de Paris.",
        acessibilidade: [
          "Elevadores Disponíveis",
          "Acesso Sem Degraus (limitado na base)",
        ],
      },
      {
        id: 18,
        destinoId: 10,
        tipoTurismo: "Turismo Cultural",
        nome: "Cruzeiro no Sena com Guia Áudio",
        foto: "https://placehold.co/600x400/FF8C00/000000?text=Atividade+Paris+3",
        descricao: "Veja os monumentos parisienses a partir do rio.",
        acessibilidade: ["Acesso Sem Degraus (barco variável)", "Guia Áudio"],
      },
      {
        id: 19,
        destinoId: 8,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita ao Museu d'Orsay",
        foto: "https://placehold.co/600x400/FF4500/FFFFFF?text=Atividade+Paris+4",
        descricao: "Explore a arte impressionista e pós-impressionista.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
        ],
      },
      {
        id: 20,
        destinoId: 9,
        tipoTurismo: "Turismo Urbano",
        nome: "Passeio Guiado por Montmartre e Sacré-Cœur",
        foto: "https://placehold.co/600x400/FF0000/000000?text=Atividade+Paris+5",
        descricao: "Descubra o bairro dos artistas e a basílica.",
        acessibilidade: [
          "Acesso Sem Degraus (muito limitado)",
          "Percurso com subidas",
        ],
      },
      {
        id: 21,
        destinoId: 11,
        tipoTurismo: "Turismo Histórico",
        nome: "Bilhete para a Casa de Anne Frank",
        foto: "https://placehold.co/600x400/008080/FFFFFF?text=Atividade+Amesterdão+1",
        descricao: "Visite o anexo secreto e conheça a história.",
        acessibilidade: [
          "Acesso Sem Degraus (limitado)",
          "Espaços apertados",
          "Necessário reservar com antecedência",
        ],
      },
      {
        id: 22,
        destinoId: 11,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita ao Rijksmuseum com Obras de Rembrandt",
        foto: "https://placehold.co/600x400/48D1CC/000000?text=Atividade+Amesterdão+2",
        descricao: "Veja a 'Ronda da Noite' e outros mestres holandeses.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
          "Guia Áudio",
        ],
      },
      {
        id: 23,
        destinoId: 11,
        tipoTurismo: "Turismo Cultural",
        nome: "Passeio de Barco Clássico pelos Canais",
        foto: "https://placehold.co/600x400/40E0D0/000000?text=Atividade+Amesterdão+3",
        descricao: "Descubra a cidade a partir da água.",
        acessibilidade: ["Acesso Sem Degraus (barco variável)", "Guia Áudio"],
      },
      {
        id: 24,
        destinoId: 11,
        tipoTurismo: "Turismo Gastronómico",
        nome: "Tour de Comida de Rua e Mercados",
        foto: "https://placehold.co/600x400/00CED1/FFFFFF?text=Atividade+Amesterdão+4",
        descricao: "Prove stroopwafels, arenque e queijos locais.",
        acessibilidade: [
          "Percurso pedestre",
          "Opções Alimentares Específicas (limitado)",
        ],
      },
      {
        id: 25,
        destinoId: 11,
        tipoTurismo: "Turismo Urbano",
        nome: "Aluguer de Bicicleta por um Dia",
        foto: "https://placehold.co/600x400/5F9EA0/000000?text=Atividade+Amesterdão+5",
        descricao: "Explore Amesterdão como um local.",
        acessibilidade: ["Requer capacidade física"],
      },
      {
        id: 26,
        destinoId: 12,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita Guiada ao Museu do Prado",
        foto: "https://placehold.co/600x400/FFD700/000000?text=Atividade+Madrid+1",
        descricao: "Conheça as obras-primas de Goya, Velázquez e El Greco.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Casas de Banho Adaptadas",
          "Aluguer de Equipamento de Mobilidade",
        ],
      },
      {
        id: 27,
        destinoId: 12,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita ao Palácio Real e Jardins de Sabatini",
        foto: "https://placehold.co/600x400/FFA500/000000?text=Atividade+Madrid+2",
        descricao: "Explore a residência oficial da monarquia espanhola.",
        acessibilidade: [
          "Acesso Sem Degraus (parcial)",
          "Elevadores Disponíveis",
        ],
      },
      {
        id: 28,
        destinoId: 12,
        tipoTurismo: "Turismo Urbano",
        nome: "Passeio pelo Parque del Retiro e Barco no Lago",
        foto: "https://placehold.co/600x400/FF8C00/FFFFFF?text=Atividade+Madrid+3",
        descricao: "Relaxe no pulmão verde de Madrid.",
        acessibilidade: ["Acesso Sem Degraus", "Casas de Banho Adaptadas"],
      },
      {
        id: 29,
        destinoId: 12,
        tipoTurismo: "Turismo Gastronómico",
        nome: "Tour de Tapas pelos Bairros Históricos",
        foto: "https://placehold.co/600x400/CD853F/FFFFFF?text=Atividade+Madrid+4",
        descricao: "Descubra os sabores autênticos de Madrid.",
        acessibilidade: [
          "Percurso pedestre",
          "Opções Alimentares Específicas (informar)",
        ],
      },
      {
        id: 30,
        destinoId: 12,
        tipoTurismo: "Turismo Cultural",
        nome: "Espetáculo de Flamenco Tradicional",
        foto: "https://placehold.co/600x400/D2691E/FFFFFF?text=Atividade+Madrid+5",
        descricao: "Sinta a paixão e a arte do flamenco.",
        acessibilidade: [
          "Acesso Sem Degraus (verificar local)",
          "Ambiente com música alta",
        ],
      },
      {
        id: 31,
        destinoId: 13,
        tipoTurismo: "Turismo Histórico",
        nome: "Visita Guiada ao Coliseu, Fórum Romano e Monte Palatino",
        foto: "https://placehold.co/600x400/B22222/FFFFFF?text=Atividade+Roma+1",
        descricao: "Viaje no tempo até à Roma Antiga.",
        acessibilidade: [
          "Acesso Sem Degraus (limitado, terreno irregular)",
          "Elevadores Disponíveis (Coliseu)",
        ],
      },
      {
        id: 32,
        destinoId: 14,
        tipoTurismo: "Turismo Religioso",
        nome: "Visita aos Museus Vaticanos, Capela Sistina e Basílica de São Pedro",
        foto: "https://placehold.co/600x400/A52A2A/FFFFFF?text=Atividade+Roma+2",
        descricao: "Explore os tesouros artísticos e religiosos do Vaticano.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Aluguer de Equipamento de Mobilidade",
        ],
      },
      {
        id: 33,
        destinoId: 13,
        tipoTurismo: "Turismo Urbano",
        nome: "Passeio pela Fontana di Trevi e Panteão",
        foto: "https://placehold.co/600x400/8B0000/FFFFFF?text=Atividade+Roma+3",
        descricao: "Visite dois dos monumentos mais icónicos de Roma.",
        acessibilidade: ["Acesso Sem Degraus (Panteão)", "Multidões"],
      },
      {
        id: 34,
        destinoId: 14,
        tipoTurismo: "Turismo Gastronómico",
        nome: "Aula de Culinária: Pasta e Tiramisu",
        foto: "https://placehold.co/600x400/800000/FFFFFF?text=Atividade+Roma+4",
        descricao: "Aprenda a cozinhar pratos italianos clássicos.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Opções Alimentares Específicas (informar)",
        ],
      },
      {
        id: 35,
        destinoId: 13,
        tipoTurismo: "Turismo Cultural",
        nome: "Visita à Galeria Borghese e Jardins",
        foto: "https://placehold.co/600x400/A0522D/FFFFFF?text=Atividade+Roma+5",
        descricao: "Admire esculturas de Bernini e pinturas de Caravaggio.",
        acessibilidade: [
          "Acesso Sem Degraus",
          "Elevadores Disponíveis",
          "Necessário reservar com antecedência",
        ],
      },
    ];
    localStorage.setItem("atividades", JSON.stringify(atividades));
  }
  // Tipos de Turismo
  if (!localStorage.tiposTurismo) {
    const tiposTurismo = [
      "Turismo religioso",
      "Turismo cultural",
      "Ecoturismo",
      "Turismo rural",
      "Turismo gastronómico",
      "Turismo de Sol e Praia",
      "Turismo de negócios",
      "Saúde e Bem-Estar",
      "Turismo Urbano",
    ];
    localStorage.setItem("tiposTurismo", JSON.stringify(tiposTurismo));
  }
  // Acessibilidade
  if (!localStorage.acessibilidade) {
    const acessibilidade = [
      "Acesso Sem Degraus",
      "Elevadores Disponíveis",
      "Casas de Banho Adaptadas",
      "Quartos Adaptados",
      "Transporte Acessível",
      "Informação em Braille/Áudio",
      "Alarmes Visuais/Vibratórios",
      "Aceita Cães-Guia/Assistência",
      "Ambientes Sensoriais Calmos",
      "Opções Alimentares Específicas",
      "Comunicação Visual/Simplificada",
      "Aluguer de Equipamento de Mobilidade",
      "Superfícies Táteis/Guia",
      "Proximidade a Serviços Médicos",
      "Ambiente Acolhedor LGBTQIA+",
      "Alojamento Inclusivo Declarado",
      "Negócios de Proprietários de Minorias",
      "Casas de Banho Neutras em Género",
    ];
    localStorage.setItem("acessibilidade", JSON.stringify(acessibilidade));
  }
  // Viagens
  if (!localStorage.viagens) {
    const viagens = [
      {
        numeroVoo: "TP2456",
        origem: "OPO - Porto",
        destino: "Lisboa",
        companhia: "TAP",
        partida: "01/07/2025 08:15",
        chegada: "01/07/2025 09:10",
        direto: "S",
        custo: 75,
        imagem: "https://placehold.co/413x327",
        dataVolta: "05/07/2025 08:15",
        turismo: ["Turismocultural", "Turismogastronomico", "TurismoUrbano"],
      },
      {
        numeroVoo: "TP2457",
        origem: "LIS - Lisboa",
        destino: "Porto",
        companhia: "TAP",
        partida: "03/07/2025 10:00",
        chegada: "03/07/2025 10:55",
        direto: "S",
        custo: 80,
        imagem: "https://placehold.co/413x327",
        dataVolta: "08/07/2025 10:00",
        turismo: ["Turismocultural", "Turismoreligioso", "TurismoUrbano"],
      },
      {
        numeroVoo: "BA1001",
        origem: "OPO - Porto",
        destino: "Londres",
        companhia: "British Airways",
        partida: "05/07/2025 06:30",
        chegada: "05/07/2025 08:30",
        direto: "S",
        custo: 200,
        imagem: "https://placehold.co/413x327",
        dataVolta: "10/07/2025 06:30",
        turismo: ["TurismoUrbano", "Turismocultural", "Turismodenegocios"],
      },
      {
        numeroVoo: "BA1002",
        origem: "LHR - Londres",
        destino: "Porto",
        companhia: "British Airways",
        partida: "07/07/2025 14:00",
        chegada: "07/07/2025 16:00",
        direto: "S",
        custo: 210,
        imagem: "https://placehold.co/413x327",
        dataVolta: "12/07/2025 14:00",
        turismo: ["Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "AF150",
        origem: "LIS - Lisboa",
        destino: "Paris",
        companhia: "Air France",
        partida: "09/07/2025 09:45",
        chegada: "09/07/2025 12:15",
        direto: "S",
        custo: 180,
        imagem: "https://placehold.co/413x327",
        dataVolta: "14/07/2025 09:45",
        turismo: ["TurismoUrbano", "Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "AF151",
        origem: "CDG - Paris",
        destino: "Lisboa",
        companhia: "Air France",
        partida: "11/07/2025 15:30",
        chegada: "11/07/2025 17:50",
        direto: "S",
        custo: 190,
        imagem: "https://placehold.co/413x327",
        dataVolta: "16/07/2025 15:30",
        turismo: ["TurismodeSolePraia", "TurismoUrbano"],
      },
      {
        numeroVoo: "KL110",
        origem: "AMS - Amesterdão",
        destino: "Roma",
        companhia: "KLM",
        partida: "13/07/2025 07:00",
        chegada: "13/07/2025 09:00",
        direto: "S",
        custo: 220,
        imagem: "https://placehold.co/413x327",
        dataVolta: "18/07/2025 07:00",
        turismo: ["Turismoreligioso", "Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "KL111",
        origem: "AMS - Amesterdão",
        destino: "Roma",
        companhia: "KLM",
        partida: "15/07/2025 12:00",
        chegada: "15/07/2025 14:30",
        direto: "S",
        custo: 230,
        imagem: "https://placehold.co/413x327",
        dataVolta: "20/07/2025 12:00",
        turismo: ["Turismoreligioso", "Turismogastronomico"],
      },
      {
        numeroVoo: "FR300",
        origem: "STN - Londres",
        destino: "Lisboa",
        companhia: "Ryanair",
        partida: "17/07/2025 06:50",
        chegada: "17/07/2025 10:30",
        direto: "N",
        custo: 90,
        imagem: "https://placehold.co/413x327",
        dataVolta: "22/07/2025 06:50",
        turismo: ["TurismodeSolePraia", "Turismocultural"],
      },
      {
        numeroVoo: "FR301",
        origem: "LIS - Lisboa",
        destino: "Londres",
        companhia: "Ryanair",
        partida: "19/07/2025 11:20",
        chegada: "19/07/2025 13:00",
        direto: "N",
        custo: 95,
        imagem: "https://placehold.co/413x327",
        dataVolta: "24/07/2025 11:20",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "BA200",
        origem: "LGW - Londres",
        destino: "Madrid",
        companhia: "British Airways",
        partida: "21/07/2025 07:15",
        chegada: "21/07/2025 10:30",
        direto: "S",
        custo: 150,
        imagem: "https://placehold.co/413x327",
        dataVolta: "26/07/2025 07:15",
        turismo: ["Turismocultural", "Turismogastronomico", "TurismoUrbano"],
      },
      {
        numeroVoo: "BA201",
        origem: "MAD - Madrid",
        destino: "Londres",
        companhia: "British Airways",
        partida: "23/07/2025 12:00",
        chegada: "23/07/2025 15:00",
        direto: "S",
        custo: 155,
        imagem: "https://placehold.co/413x327",
        dataVolta: "28/07/2025 12:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "U2789",
        origem: "LTN - Londres",
        destino: "Amesterdão",
        companhia: "EasyJet",
        partida: "25/07/2025 08:00",
        chegada: "25/07/2025 11:10",
        direto: "S",
        custo: 120,
        imagem: "https://placehold.co/413x327",
        dataVolta: "30/07/2025 08:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "U2790",
        origem: "AMS - Amesterdão",
        destino: "Londres",
        companhia: "EasyJet",
        partida: "27/07/2025 18:20",
        chegada: "27/07/2025 21:30",
        direto: "S",
        custo: 125,
        imagem: "https://placehold.co/413x327",
        dataVolta: "01/08/2025 18:20",
        turismo: ["TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "AF2000",
        origem: "ORY - Paris",
        destino: "Londres",
        companhia: "Air France",
        partida: "29/07/2025 09:00",
        chegada: "29/07/2025 10:15",
        direto: "N",
        custo: 110,
        imagem: "https://placehold.co/413x327",
        dataVolta: "03/08/2025 09:00",
        turismo: ["TurismoUrbano", "Turismocultural"],
      },
      {
        numeroVoo: "FR305",
        origem: "STN - Londres",
        destino: "Paris",
        companhia: "Ryanair",
        partida: "02/08/2025 14:00",
        chegada: "02/08/2025 18:00",
        direto: "N",
        custo: 95,
        imagem: "https://placehold.co/413x327",
        dataVolta: "07/08/2025 14:00",
        turismo: ["TurismoUrbano", "Turismogastronomico"],
      },
      {
        numeroVoo: "AF2010",
        origem: "CDG - Paris",
        destino: "Paris",
        companhia: "Air France",
        partida: "04/08/2025 10:00",
        chegada: "04/08/2025 10:45",
        direto: "S",
        custo: 100,
        imagem: "https://placehold.co/413x327",
        dataVolta: "09/08/2025 10:00",
        turismo: ["TurismoUrbano", "Turismocultural"],
      },
      {
        numeroVoo: "AF2011",
        origem: "BVA - Paris",
        destino: "Paris",
        companhia: "Air France",
        partida: "06/08/2025 12:00",
        chegada: "06/08/2025 12:45",
        direto: "S",
        custo: 100,
        imagem: "https://placehold.co/413x327",
        dataVolta: "11/08/2025 12:00",
        turismo: ["TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "KL115",
        origem: "LIS - Lisboa",
        destino: "Amesterdão",
        companhia: "KLM",
        partida: "08/08/2025 07:00",
        chegada: "08/08/2025 09:30",
        direto: "S",
        custo: 170,
        imagem: "https://placehold.co/413x327",
        dataVolta: "13/08/2025 07:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "KL116",
        origem: "AMS - Amesterdão",
        destino: "Lisboa",
        companhia: "KLM",
        partida: "10/08/2025 13:00",
        chegada: "10/08/2025 15:30",
        direto: "S",
        custo: 175,
        imagem: "https://placehold.co/413x327",
        dataVolta: "15/08/2025 13:00",
        turismo: ["TurismodeSolePraia", "Turismogastronomico"],
      },
      {
        numeroVoo: "AZ320",
        origem: "CIA - Roma",
        destino: "Madrid",
        companhia: "Alitalia",
        partida: "12/08/2025 06:30",
        chegada: "12/08/2025 08:45",
        direto: "N",
        custo: 200,
        imagem: "https://placehold.co/413x327",
        dataVolta: "17/08/2025 06:30",
        turismo: ["Turismocultural", "Turismogastronomico", "TurismoUrbano"],
      },
      {
        numeroVoo: "AZ321",
        origem: "MAD - Madrid",
        destino: "Roma",
        companhia: "Alitalia",
        partida: "14/08/2025 17:00",
        chegada: "14/08/2025 19:15",
        direto: "N",
        custo: 205,
        imagem: "https://placehold.co/413x327",
        dataVolta: "19/08/2025 17:00",
        turismo: ["Turismoreligioso", "Turismocultural"],
      },
      {
        numeroVoo: "BA550",
        origem: "LGW - Londres",
        destino: "Londres",
        companhia: "British Airways",
        partida: "16/08/2025 09:00",
        chegada: "16/08/2025 10:00",
        direto: "S",
        custo: 80,
        imagem: "https://placehold.co/413x327",
        dataVolta: "21/08/2025 09:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "BA551",
        origem: "LCY - Londres",
        destino: "Londres",
        companhia: "British Airways",
        partida: "18/08/2025 12:30",
        chegada: "18/08/2025 13:30",
        direto: "S",
        custo: 85,
        imagem: "https://placehold.co/413x327",
        dataVolta: "23/08/2025 12:30",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "TP300",
        origem: "LHR - Londres",
        destino: "Lisboa",
        companhia: "TAP",
        partida: "20/08/2025 08:00",
        chegada: "20/08/2025 11:00",
        direto: "S",
        custo: 160,
        imagem: "https://placehold.co/413x327",
        dataVolta: "25/08/2025 08:00",
        turismo: [
          "TurismodeSolePraia",
          "Turismocultural",
          "Turismogastronomico",
        ],
      },
      {
        numeroVoo: "TP301",
        origem: "LIS - Lisboa",
        destino: "Londres",
        companhia: "TAP",
        partida: "22/08/2025 14:00",
        chegada: "22/08/2025 17:00",
        direto: "S",
        custo: 165,
        imagem: "https://placehold.co/413x327",
        dataVolta: "27/08/2025 14:00",
        turismo: ["Turismodenegocios", "TurismoUrbano", "Turismocultural"],
      },
      {
        numeroVoo: "VY821",
        origem: "STN - Londres",
        destino: "Madrid",
        companhia: "Vueling",
        partida: "24/08/2025 07:15",
        chegada: "24/08/2025 10:15",
        direto: "N",
        custo: 120,
        imagem: "https://placehold.co/413x327",
        dataVolta: "29/08/2025 07:15",
        turismo: ["Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "VY822",
        origem: "MAD - Madrid",
        destino: "Londres",
        companhia: "Vueling",
        partida: "26/08/2025 12:00",
        chegada: "26/08/2025 15:00",
        direto: "N",
        custo: 125,
        imagem: "https://placehold.co/413x327",
        dataVolta: "31/08/2025 12:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "SN100",
        origem: "BVA - Paris",
        destino: "Amesterdão",
        companhia: "Brussels Airlines",
        partida: "01/09/2025 09:00",
        chegada: "01/09/2025 10:30",
        direto: "S",
        custo: 95,
        imagem: "https://placehold.co/413x327",
        dataVolta: "06/09/2025 09:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "SN101",
        origem: "AMS - Amesterdão",
        destino: "Paris",
        companhia: "Brussels Airlines",
        partida: "03/09/2025 12:00",
        chegada: "03/09/2025 13:30",
        direto: "S",
        custo: 100,
        imagem: "https://placehold.co/413x327",
        dataVolta: "08/09/2025 12:00",
        turismo: ["TurismoUrbano", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1001",
        origem: "AMS - Amesterdão",
        destino: "Londres",
        companhia: "TAP",
        partida: "05/09/2025 06:00",
        chegada: "05/09/2025 08:00",
        direto: "S",
        custo: 150,
        imagem: "https://placehold.co/413x327",
        dataVolta: "10/09/2025 06:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "OP1002",
        origem: "CDG - Paris",
        destino: "Londres",
        companhia: "Ryanair",
        partida: "07/09/2025 09:30",
        chegada: "07/09/2025 11:45",
        direto: "N",
        custo: 85,
        imagem: "https://placehold.co/413x327",
        dataVolta: "12/09/2025 09:30",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "OP1003",
        origem: "ORY - Paris",
        destino: "Londres",
        companhia: "EasyJet",
        partida: "09/09/2025 07:15",
        chegada: "09/09/2025 09:30",
        direto: "S",
        custo: 120,
        imagem: "https://placehold.co/413x327",
        dataVolta: "14/09/2025 07:15",
        turismo: ["TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1004",
        origem: "FCO - Roma",
        destino: "Londres",
        companhia: "TAP",
        partida: "11/09/2025 12:00",
        chegada: "11/09/2025 14:15",
        direto: "S",
        custo: 140,
        imagem: "https://placehold.co/413x327",
        dataVolta: "16/09/2025 12:00",
        turismo: ["Turismocultural", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1005",
        origem: "CIA - Roma",
        destino: "Paris",
        companhia: "Air France",
        partida: "13/09/2025 08:45",
        chegada: "13/09/2025 11:10",
        direto: "N",
        custo: 160,
        imagem: "https://placehold.co/413x327",
        dataVolta: "18/09/2025 08:45",
        turismo: ["Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1006",
        origem: "LCY - Londres",
        destino: "Paris",
        companhia: "KLM",
        partida: "15/09/2025 13:00",
        chegada: "15/09/2025 15:05",
        direto: "S",
        custo: 170,
        imagem: "https://placehold.co/413x327",
        dataVolta: "20/09/2025 13:00",
        turismo: ["TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1007",
        origem: "BVA - Paris",
        destino: "Paris",
        companhia: "Brussels Airlines",
        partida: "17/09/2025 06:30",
        chegada: "17/09/2025 08:00",
        direto: "S",
        custo: 130,
        imagem: "https://placehold.co/413x327",
        dataVolta: "22/09/2025 06:30",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "OP1008",
        origem: "CDG - Paris",
        destino: "Amesterdão",
        companhia: "Ryanair",
        partida: "19/09/2025 10:00",
        chegada: "19/09/2025 13:00",
        direto: "N",
        custo: 95,
        imagem: "https://placehold.co/413x327",
        dataVolta: "24/09/2025 10:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "OP1009",
        origem: "AMS - Amesterdão",
        destino: "Madrid",
        companhia: "TAP",
        partida: "21/09/2025 07:00",
        chegada: "21/09/2025 09:15",
        direto: "S",
        custo: 145,
        imagem: "https://placehold.co/413x327",
        dataVolta: "26/09/2025 07:00",
        turismo: ["Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1010",
        origem: "MAD - Madrid",
        destino: "Roma",
        companhia: "Alitalia",
        partida: "23/09/2025 11:45",
        chegada: "23/09/2025 13:50",
        direto: "N",
        custo: 180,
        imagem: "https://placehold.co/413x327",
        dataVolta: "28/09/2025 11:45",
        turismo: ["Turismoreligioso", "Turismocultural"],
      },
      {
        numeroVoo: "OP1011",
        origem: "LGW - Londres",
        destino: "Roma",
        companhia: "British Airways",
        partida: "25/09/2025 06:15",
        chegada: "25/09/2025 08:45",
        direto: "S",
        custo: 155,
        imagem: "https://placehold.co/413x327",
        dataVolta: "30/09/2025 06:15",
        turismo: ["Turismoreligioso", "Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1012",
        origem: "CDG - Paris",
        destino: "Roma",
        companhia: "EasyJet",
        partida: "27/09/2025 10:30",
        chegada: "27/09/2025 12:00",
        direto: "S",
        custo: 125,
        imagem: "https://placehold.co/413x327",
        dataVolta: "02/10/2025 10:30",
        turismo: ["Turismoreligioso", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1013",
        origem: "LHR - Londres",
        destino: "Paris",
        companhia: "TAP",
        partida: "01/10/2025 08:00",
        chegada: "01/10/2025 09:20",
        direto: "S",
        custo: 75,
        imagem: "https://placehold.co/413x327",
        dataVolta: "06/10/2025 08:00",
        turismo: ["Turismocultural", "TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1014",
        origem: "FCO - Roma",
        destino: "Londres",
        companhia: "Ryanair",
        partida: "03/10/2025 12:00",
        chegada: "03/10/2025 14:20",
        direto: "N",
        custo: 95,
        imagem: "https://placehold.co/413x327",
        dataVolta: "08/10/2025 12:00",
        turismo: ["TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1015",
        origem: "CIA - Roma",
        destino: "Londres",
        companhia: "KLM",
        partida: "05/10/2025 07:45",
        chegada: "05/10/2025 09:50",
        direto: "S",
        custo: 160,
        imagem: "https://placehold.co/413x327",
        dataVolta: "10/10/2025 07:45",
        turismo: ["TurismoUrbano", "Turismocultural"],
      },
      {
        numeroVoo: "OP1016",
        origem: "AMS - Amesterdão",
        destino: "Londres",
        companhia: "TAP",
        partida: "07/10/2025 13:00",
        chegada: "07/10/2025 15:10",
        direto: "S",
        custo: 135,
        imagem: "https://placehold.co/413x327",
        dataVolta: "12/10/2025 13:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "OP1017",
        origem: "OPO - Porto",
        destino: "Londres",
        companhia: "Air France",
        partida: "09/10/2025 06:30",
        chegada: "09/10/2025 08:55",
        direto: "N",
        custo: 165,
        imagem: "https://placehold.co/413x327",
        dataVolta: "14/10/2025 06:30",
        turismo: ["Turismocultural", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1018",
        origem: "OPO - Porto",
        destino: "Paris",
        companhia: "Brussels Airlines",
        partida: "11/10/2025 11:15",
        chegada: "11/10/2025 13:20",
        direto: "S",
        custo: 150,
        imagem: "https://placehold.co/413x327",
        dataVolta: "16/10/2025 11:15",
        turismo: ["TurismoUrbano", "Turismogastronomico"],
      },
      {
        numeroVoo: "OP1019",
        origem: "OPO - Porto",
        destino: "Paris",
        companhia: "EasyJet",
        partida: "13/10/2025 07:00",
        chegada: "13/10/2025 09:30",
        direto: "S",
        custo: 140,
        imagem: "https://placehold.co/413x327",
        dataVolta: "18/10/2025 07:00",
        turismo: ["Turismocultural", "Turismodenegocios"],
      },
      {
        numeroVoo: "OP1020",
        origem: "OPO - Porto",
        destino: "Paris",
        companhia: "Ryanair",
        partida: "15/10/2025 12:00",
        chegada: "15/10/2025 14:45",
        direto: "N",
        custo: 100,
        imagem: "https://placehold.co/413x327",
        dataVolta: "20/10/2025 12:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "TP1234",
        origem: "OPO - Porto",
        destino: "Madrid",
        companhia: "TAP Air Portugal",
        partida: "17/10/2025 10:00",
        chegada: "17/10/2025 11:30",
        direto: "S",
        custo: 85,
        imagem: "https://placehold.co/413x327",
        dataVolta: "22/10/2025 14:00",
        turismo: ["Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "FR5678",
        origem: "OPO - Porto",
        destino: "Paris",
        companhia: "Ryanair",
        partida: "19/10/2025 12:00",
        chegada: "19/10/2025 14:45",
        direto: "S",
        custo: 100,
        imagem: "https://placehold.co/413x327",
        dataVolta: "24/10/2025 12:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "EZY9101",
        origem: "OPO - Porto",
        destino: "Londres",
        companhia: "easyJet",
        partida: "21/10/2025 08:30",
        chegada: "21/10/2025 11:00",
        direto: "S",
        custo: 120,
        imagem: "https://placehold.co/413x327",
        dataVolta: "26/10/2025 16:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "BA2345",
        origem: "OPO - Porto",
        destino: "Dublin",
        companhia: "British Airways",
        partida: "23/10/2025 14:00",
        chegada: "23/10/2025 16:00",
        direto: "N",
        custo: 180,
        imagem: "https://placehold.co/413x327",
        dataVolta: "28/10/2025 10:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "LH6789",
        origem: "OPO - Porto",
        destino: "Berlim",
        companhia: "Lufthansa",
        partida: "25/10/2025 09:00",
        chegada: "25/10/2025 12:30",
        direto: "S",
        custo: 150,
        imagem: "https://placehold.co/413x327",
        dataVolta: "30/10/2025 15:00",
        turismo: ["Turismocultural", "TurismoUrbano", "Turismodenegocios"],
      },
      {
        numeroVoo: "IB3456",
        origem: "OPO - Porto",
        destino: "Barcelona",
        companhia: "Iberia",
        partida: "27/10/2025 11:00",
        chegada: "27/10/2025 13:00",
        direto: "S",
        custo: 90,
        imagem: "https://placehold.co/413x327",
        dataVolta: "01/11/2025 18:00",
        turismo: [
          "TurismodeSolePraia",
          "Turismocultural",
          "Turismogastronomico",
        ],
      },
      {
        numeroVoo: "KL7890",
        origem: "OPO - Porto",
        destino: "Amsterdão",
        companhia: "KLM",
        partida: "02/11/2025 13:00",
        chegada: "02/11/2025 16:00",
        direto: "S",
        custo: 160,
        imagem: "https://placehold.co/413x327",
        dataVolta: "07/11/2025 11:00",
        turismo: ["Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "SK1234",
        origem: "OPO - Porto",
        destino: "Copenhaga",
        companhia: "SAS",
        partida: "04/11/2025 07:00",
        chegada: "04/11/2025 10:30",
        direto: "N",
        custo: 200,
        imagem: "https://placehold.co/413x327",
        dataVolta: "09/11/2025 09:00",
        turismo: ["Turismocultural", "Ecoturismo"],
      },
      {
        numeroVoo: "AF5678",
        origem: "OPO - Porto",
        destino: "Roma",
        companhia: "Air France",
        partida: "06/11/2025 10:00",
        chegada: "06/11/2025 13:00",
        direto: "S",
        custo: 140,
        imagem: "https://placehold.co/413x327",
        dataVolta: "11/11/2025 17:00",
        turismo: ["Turismoreligioso", "Turismocultural", "Turismogastronomico"],
      },
      {
        numeroVoo: "VY9101",
        origem: "OPO - Porto",
        destino: "Milão",
        companhia: "Vueling",
        partida: "08/11/2025 15:00",
        chegada: "08/11/2025 17:30",
        direto: "S",
        custo: 95,
        imagem: "https://placehold.co/413x327",
        dataVolta: "13/11/2025 19:00",
        turismo: ["Turismodenegocios", "Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "TK2345",
        origem: "OPO - Porto",
        destino: "Istambul",
        companhia: "Turkish Airlines",
        partida: "10/11/2025 18:00",
        chegada: "10/11/2025 23:00",
        direto: "N",
        custo: 250,
        imagem: "https://placehold.co/413x327",
        dataVolta: "15/11/2025 14:00",
        turismo: ["Turismoreligioso", "Turismocultural", "Turismodenegocios"],
      },
      {
        numeroVoo: "LX6789",
        origem: "OPO - Porto",
        destino: "Zurique",
        companhia: "SWISS",
        partida: "12/11/2025 09:00",
        chegada: "12/11/2025 12:00",
        direto: "S",
        custo: 170,
        imagem: "https://placehold.co/413x327",
        dataVolta: "17/11/2025 10:00",
        turismo: ["Turismodenegocios", "Ecoturismo", "SaudeeBemEstar"],
      },
      {
        numeroVoo: "AUA1234",
        origem: "OPO - Porto",
        destino: "Viena",
        companhia: "Austrian Airlines",
        partida: "14/11/2025 11:00",
        chegada: "14/11/2025 14:30",
        direto: "S",
        custo: 155,
        imagem: "https://placehold.co/413x327",
        dataVolta: "19/11/2025 13:00",
        turismo: ["Turismocultural", "SaudeeBemEstar", "TurismoUrbano"],
      },
      {
        numeroVoo: "DY5678",
        origem: "OPO - Porto",
        destino: "Oslo",
        companhia: "Norwegian Air Shuttle",
        partida: "16/11/2025 16:00",
        chegada: "16/11/2025 19:00",
        direto: "N",
        custo: 210,
        imagem: "https://placehold.co/413x327",
        dataVolta: "21/11/2025 08:00",
        turismo: ["Ecoturismo", "Turismocultural"],
      },
      {
        numeroVoo: "EI9101",
        origem: "OPO - Porto",
        destino: "Dublin",
        companhia: "Aer Lingus",
        partida: "18/11/2025 08:00",
        chegada: "18/11/2025 10:00",
        direto: "S",
        custo: 130,
        imagem: "https://placehold.co/413x327",
        dataVolta: "23/11/2025 16:00",
        turismo: ["Turismocultural", "TurismoUrbano", "Turismogastronomico"],
      },
      {
        numeroVoo: "AZ2345",
        origem: "OPO - Porto",
        destino: "Florença",
        companhia: "ITA Airways",
        partida: "20/11/2025 13:00",
        chegada: "20/11/2025 16:00",
        direto: "N",
        custo: 190,
        imagem: "https://placehold.co/413x327",
        dataVolta: "25/11/2025 10:00",
        turismo: ["Turismocultural", "Turismorural", "Turismogastronomico"],
      },
      {
        numeroVoo: "SN6789",
        origem: "OPO - Porto",
        destino: "Bruxelas",
        companhia: "Brussels Airlines",
        partida: "22/11/2025 10:00",
        chegada: "22/11/2025 12:30",
        direto: "S",
        custo: 115,
        imagem: "https://placehold.co/413x327",
        dataVolta: "27/11/2025 15:00",
        turismo: ["Turismodenegocios", "Turismogastronomico", "TurismoUrbano"],
      },
      {
        numeroVoo: "LO1234",
        origem: "OPO - Porto",
        destino: "Varsóvia",
        companhia: "LOT Polish Airlines",
        partida: "24/11/2025 14:00",
        chegada: "24/11/2025 17:30",
        direto: "N",
        custo: 220,
        imagem: "https://placehold.co/413x327",
        dataVolta: "29/11/2025 09:00",
        turismo: ["Turismocultural", "Turismoreligioso", "TurismoUrbano"],
      },
      {
        numeroVoo: "RO5678",
        origem: "OPO - Porto",
        destino: "Bucareste",
        companhia: "TAROM",
        partida: "26/11/2025 09:30",
        chegada: "26/11/2025 13:00",
        direto: "N",
        custo: 230,
        imagem: "https://placehold.co/413x327",
        dataVolta: "01/12/2025 11:00",
        turismo: ["Turismocultural", "Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "H69101",
        origem: "OPO - Porto",
        destino: "Budapeste",
        companhia: "Wizz Air",
        partida: "28/11/2025 17:00",
        chegada: "28/11/2025 20:00",
        direto: "S",
        custo: 80,
        imagem: "https://placehold.co/413x327",
        dataVolta: "03/12/2025 14:00",
        turismo: ["Turismocultural", "SaudeeBemEstar", "TurismoUrbano"],
      },
      {
        numeroVoo: "AY2345",
        origem: "OPO - Porto",
        destino: "Helsínquia",
        companhia: "Finnair",
        partida: "01/12/2025 12:00",
        chegada: "01/12/2025 16:00",
        direto: "N",
        custo: 260,
        imagem: "https://placehold.co/413x327",
        dataVolta: "06/12/2025 10:00",
        turismo: ["Ecoturismo", "Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "LX6789",
        origem: "OPO - Porto",
        destino: "Genebra",
        companhia: "SWISS",
        partida: "03/12/2025 08:00",
        chegada: "03/12/2025 11:00",
        direto: "S",
        custo: 165,
        imagem: "https://placehold.co/413x327",
        dataVolta: "08/12/2025 17:00",
        turismo: [
          "Turismodenegocios",
          "Ecoturismo",
          "TurismoUrbano",
          "SaudeeBemEstar",
        ],
      },
      {
        numeroVoo: "FR1020",
        origem: "OPO - Porto",
        destino: "Frankfurt",
        companhia: "Ryanair",
        partida: "05/12/2025 11:00",
        chegada: "05/12/2025 14:00",
        direto: "S",
        custo: 105,
        imagem: "https://placehold.co/413x327",
        dataVolta: "10/12/2025 12:00",
        turismo: ["Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "TP3040",
        origem: "OPO - Porto",
        destino: "Munique",
        companhia: "TAP Air Portugal",
        partida: "07/12/2025 15:00",
        chegada: "07/12/2025 18:30",
        direto: "S",
        custo: 135,
        imagem: "https://placehold.co/413x327",
        dataVolta: "12/12/2025 16:00",
        turismo: [
          "Turismocultural",
          "Turismogastronomico",
          "Turismodenegocios",
        ],
      },
      {
        numeroVoo: "EZY5060",
        origem: "OPO - Porto",
        destino: "Manchester",
        companhia: "easyJet",
        partida: "09/12/2025 09:00",
        chegada: "09/12/2025 11:30",
        direto: "S",
        custo: 110,
        imagem: "https://placehold.co/413x327",
        dataVolta: "14/12/2025 14:00",
        turismo: ["Turismocultural", "Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "BA7080",
        origem: "OPO - Porto",
        destino: "Edimburgo",
        companhia: "British Airways",
        partida: "11/12/2025 13:00",
        chegada: "11/12/2025 15:30",
        direto: "N",
        custo: 195,
        imagem: "https://placehold.co/413x327",
        dataVolta: "16/12/2025 10:00",
        turismo: ["Turismocultural", "Turismoreligioso", "TurismoUrbano"],
      },
      {
        numeroVoo: "LH9010",
        origem: "OPO - Porto",
        destino: "Hamburgo",
        companhia: "Lufthansa",
        partida: "13/12/2025 10:00",
        chegada: "13/12/2025 13:30",
        direto: "S",
        custo: 145,
        imagem: "https://placehold.co/413x327",
        dataVolta: "18/12/2025 15:00",
        turismo: ["Turismodenegocios", "Turismocultural", "TurismoUrbano"],
      },
      {
        numeroVoo: "IB2030",
        origem: "OPO - Porto",
        destino: "Valência",
        companhia: "Iberia",
        partida: "15/12/2025 12:00",
        chegada: "15/12/2025 14:00",
        direto: "S",
        custo: 90,
        imagem: "https://placehold.co/413x327",
        dataVolta: "20/12/2025 18:00",
        turismo: [
          "TurismodeSolePraia",
          "Turismogastronomico",
          "Turismocultural",
        ],
      },
      {
        numeroVoo: "KL4050",
        origem: "OPO - Porto",
        destino: "Roterdão",
        companhia: "KLM",
        partida: "17/12/2025 14:00",
        chegada: "17/12/2025 17:00",
        direto: "N",
        custo: 175,
        imagem: "https://placehold.co/413x327",
        dataVolta: "22/12/2025 11:00",
        turismo: ["TurismoUrbano", "Turismodenegocios", "Turismocultural"],
      },
      {
        numeroVoo: "SK6070",
        origem: "OPO - Porto",
        destino: "Estocolmo",
        companhia: "SAS",
        partida: "19/12/2025 08:00",
        chegada: "19/12/2025 11:30",
        direto: "N",
        custo: 225,
        imagem: "https://placehold.co/413x327",
        dataVolta: "24/12/2025 09:00",
        turismo: ["Turismocultural", "Ecoturismo", "TurismoUrbano"],
      },
      {
        numeroVoo: "AF8090",
        origem: "OPO - Porto",
        destino: "Marselha",
        companhia: "Air France",
        partida: "21/12/2025 11:00",
        chegada: "21/12/2025 13:30",
        direto: "N",
        custo: 160,
        imagem: "https://placehold.co/413x327",
        dataVolta: "26/12/2025 14:00",
        turismo: [
          "TurismodeSolePraia",
          "Turismocultural",
          "Turismogastronomico",
        ],
      },
      {
        numeroVoo: "VY1020",
        origem: "OPO - Porto",
        destino: "Sevilha",
        companhia: "Vueling",
        partida: "23/12/2025 16:00",
        chegada: "23/12/2025 17:30",
        direto: "S",
        custo: 88,
        imagem: "https://placehold.co/413x327",
        dataVolta: "28/12/2025 19:00",
        turismo: ["Turismocultural", "Turismoreligioso", "Turismogastronomico"],
      },
      {
        numeroVoo: "TK3040",
        origem: "OPO - Porto",
        destino: "Ancara",
        companhia: "Turkish Airlines",
        partida: "25/12/2025 19:00",
        chegada: "26/12/2025 00:30",
        direto: "N",
        custo: 280,
        imagem: "https://placehold.co/413x327",
        dataVolta: "30/12/2025 14:00",
        turismo: ["Turismocultural", "Turismodenegocios", "TurismoUrbano"],
      },
      {
        numeroVoo: "LX5060",
        origem: "OPO - Porto",
        destino: "Basileia",
        companhia: "SWISS",
        partida: "26/12/2025 09:00",
        chegada: "26/12/2025 12:00",
        direto: "S",
        custo: 170,
        imagem: "https://placehold.co/413x327",
        dataVolta: "29/12/2025 10:00",
        turismo: ["Turismodenegocios", "Turismocultural", "SaudeeBemEstar"],
      },
      {
        numeroVoo: "AUA7080",
        origem: "OPO - Porto",
        destino: "Salzburgo",
        companhia: "Austrian Airlines",
        partida: "27/12/2025 10:00",
        chegada: "27/12/2025 13:30",
        direto: "N",
        custo: 190,
        imagem: "https://placehold.co/413x327",
        dataVolta: "31/12/2025 13:00",
        turismo: ["Turismocultural", "Turismorural", "Ecoturismo"],
      },
      {
        numeroVoo: "DY9010",
        origem: "OPO - Porto",
        destino: "Bergen",
        companhia: "Norwegian Air Shuttle",
        partida: "28/12/2025 15:00",
        chegada: "28/12/2025 18:00",
        direto: "N",
        custo: 240,
        imagem: "https://placehold.co/413x327",
        dataVolta: "02/01/2026 08:00",
        turismo: ["Ecoturismo", "Turismocultural"],
      },
    ];
    localStorage.setItem("viagens", JSON.stringify(viagens));
  }

