name: 📋 Nova Tarefa
description: Abra uma nova tarefa, escolha prioridade e defina datas
title: "[Tarefa] "
labels: ["tarefa"]
body:
  - type: dropdown
    id: priority
    attributes:
      label: "Prioridade"
      description: "Selecione a prioridade desta tarefa"
      options:
        - "Alta"
        - "Média"
        - "Baixa"
      default: 1
    validations:
      required: true

  - type: input
    id: start_date
    attributes:
      label: "Data de início"
      description: "Data de início (hoje)"
      value: "2025-05-12"
    validations:
      required: true

  - type: input
    id: due_date
    attributes:
      label: "Data de conclusão"
      description: "Data de conclusão (15 dias após hoje)"
      value: "2025-05-27"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Descrição"
      description: "Descreva os detalhes desta tarefa"
      placeholder: "Detalhes da tarefa..."
    validations:
      required: true
